import type { Artisan, Category, Order, Product } from "./types";

const craftImages = {
  pottery: "/images/aisha/A1.jpg",
  potteryDetail: "/images/aisha/B1.jpg",
  textiles: "/images/aisha/M1.jpg",
  textilesDetail: "/images/aisha/Snapinsta.app_447895980_18152353162314221_3689087632318507403_n_1080.jpg",
  jewellery: "/images/aisha/Snapinsta.app_455131776_903354394960467_3623373114008527603_n_1080.jpg",
  jewelleryDetail: "/images/aisha/O5.jpg",
  leather: "/images/aisha/Snapinsta.app_470984486_18032514275416001_5509346141223573205_n_1080.jpg",
  metalwork: "/images/aisha/Screenshot 2025-01-04 002802.png",
  basketry: "/images/aisha/CP1.jpg",
} as const;
const image = craftImages.jewellery;
const artisanImages: Record<string, string> = {
  "atelier-tala": craftImages.jewellery,
  "maison-nahla": craftImages.textiles,
  "terre-des-aures": craftImages.pottery,
};
const productImages: Record<string, string[]> = {
  jewellery: [craftImages.jewellery, craftImages.jewelleryDetail],
  textiles: [craftImages.textiles, craftImages.textilesDetail],
  pottery: [craftImages.pottery, craftImages.potteryDetail],
  leather: [craftImages.leather],
  metalwork: [craftImages.metalwork],
  basketry: [craftImages.basketry],
};
const text = (en: string, fr: string, ar: string, es: string) => ({ en, fr, ar, es });

export const categories: Category[] = [
  { slug: "pottery", name: text("Pottery", "Poterie", "الفخار", "Cerámica"), description: text("Earth, fire, and inherited forms", "Terre, feu et formes héritées", "أرض ونار وأشكال متوارثة", "Tierra, fuego y formas heredadas"), image: craftImages.pottery },
  { slug: "textiles", name: text("Rugs & textiles", "Tapis et textiles", "السجاد والمنسوجات", "Alfombras y textiles"), description: text("Woven stories from mountain and desert", "Récits tissés de montagne et de désert", "حكايات منسوجة من الجبل والصحراء", "Historias tejidas de montaña y desierto"), image: craftImages.textiles },
  { slug: "jewellery", name: text("Traditional jewellery", "Bijoux traditionnels", "الحلي التقليدية", "Joyería tradicional"), description: text("Silver, enamel, and symbolic detail", "Argent, émail et détails symboliques", "فضة ومينا ورموز", "Plata, esmalte y detalles simbólicos"), image: craftImages.jewellery },
  { slug: "leather", name: text("Leather goods", "Maroquinerie", "المنتجات الجلدية", "Artículos de cuero"), description: text("Useful objects finished by hand", "Objets utiles finis à la main", "قطع عملية مصنوعة يدوياً", "Objetos útiles acabados a mano"), image: craftImages.leather },
  { slug: "metalwork", name: text("Copper & metalwork", "Cuivre et métal", "النحاس والمعادن", "Cobre y metal"), description: text("Hammered light and patient engraving", "Lumière martelée et gravure patiente", "نقش وصياغة بصبر", "Luz martillada y grabado paciente"), image: craftImages.metalwork },
  { slug: "basketry", name: text("Halfa & basketry", "Halfa et vannerie", "الحلفاء والسلال", "Esparto y cestería"), description: text("Natural fibres shaped for the home", "Fibres naturelles façonnées pour la maison", "ألياف طبيعية للبيت", "Fibras naturales para el hogar"), image: craftImages.basketry },
];

export const artisans: Artisan[] = [
  { slug: "atelier-tala", name: "Lila Aït Mansour", workshop: "Atelier Tala", region: text("Tizi Ouzou, Kabylia", "Tizi Ouzou, Kabylie", "تيزي وزو، القبائل", "Tizi Ouzou, Cabilia"), craft: text("Silversmithing", "Orfèvrerie", "صياغة الفضة", "Platería"), biography: text("Lila continues a family language of silver, coral tones, and precise enamel work.", "Lila perpétue un langage familial fait d’argent, de tons corail et d’émail précis.", "تواصل ليلى لغة عائلية من الفضة وألوان المرجان والمينا الدقيقة.", "Lila continúa un lenguaje familiar de plata, tonos coral y esmalte preciso."), image, verified: true, productCount: 2 },
  { slug: "maison-nahla", name: "Nahla Benali", workshop: "Maison Nahla", region: text("Ghardaïa, M’Zab", "Ghardaïa, M’Zab", "غرداية، مزاب", "Ghardaïa, M’Zab"), craft: text("Weaving", "Tissage", "النسيج", "Tejido"), biography: text("Nahla works with wool and geometric rhythms inspired by the M’Zab valley.", "Nahla travaille la laine et les rythmes géométriques inspirés de la vallée du M’Zab.", "تعمل نهلة بالصوف والإيقاعات الهندسية المستوحاة من وادي مزاب.", "Nahla trabaja la lana y ritmos geométricos inspirados en el valle del M’Zab."), image, verified: true, productCount: 2 },
  { slug: "terre-des-aures", name: "Samira Boudiaf", workshop: "Terre des Aurès", region: text("Batna, Aurès", "Batna, Aurès", "باتنة، الأوراس", "Batna, Aurès"), craft: text("Pottery", "Poterie", "الفخار", "Cerámica"), biography: text("Samira shapes quiet vessels with local clay and hand-painted marks.", "Samira façonne des pièces sobres en argile locale, peintes à la main.", "تشكّل سميرة أواني هادئة من الطين المحلي وتزينها يدوياً.", "Samira crea vasijas serenas con arcilla local y marcas pintadas a mano."), image, verified: true, productCount: 2 },
].map((artisan) => ({ ...artisan, image: artisanImages[artisan.slug] }));

export const products: Product[] = ([
  { slug:"kabyle-silver-brooch",name:text("Kabyle silver brooch","Broche kabyle en argent","بروش قبائلي فضي","Broche cabila de plata"),summary:text("A hand-enamelled silver brooch inspired by protective fibula forms.","Une broche en argent émaillé à la main inspirée des fibules protectrices.","بروش فضي مطلي بالمينا يدوياً مستوحى من أشكال الخلالة.","Un broche de plata esmaltado a mano inspirado en fíbulas protectoras."),story:text("Each line is engraved before colour is placed by hand, joining adornment with a living Kabyle visual language.","Chaque ligne est gravée avant la pose manuelle de la couleur, unissant parure et langage visuel kabyle vivant.","يُنقش كل خط قبل وضع اللون باليد، جامعاً الزينة بلغة بصرية قبائلية حية.","Cada línea se graba antes de aplicar el color a mano, uniendo adorno y lenguaje visual cabila."),artisanSlug:"atelier-tala",categorySlug:"jewellery",region:text("Kabylia","Kabylie","القبائل","Cabilia"),materials:text("Silver and enamel","Argent et émail","فضة ومينا","Plata y esmalte"),method:text("Hand engraving and enamel","Gravure et émail à la main","نقش ومينا يدوياً","Grabado y esmalte a mano"),priceMinor:12500,currency:"EUR",availability:"low_stock",images:[image,image],featured:true,new:true,rating:4.9,reviewCount:28},
  { slug:"mzab-wool-cushion",name:text("M’Zab wool cushion","Coussin en laine du M’Zab","وسادة صوفية مزابية","Cojín de lana del M’Zab"),summary:text("A dense handwoven cushion in earth and date-palm tones.","Un coussin dense tissé à la main dans des tons terre et palmier.","وسادة منسوجة يدوياً بألوان الأرض والنخيل.","Un cojín tejido a mano en tonos tierra y palmera."),story:text("Geometric bands recall the architecture and measured rhythm of the M’Zab valley.","Les bandes géométriques rappellent l’architecture et le rythme mesuré de la vallée du M’Zab.","تستحضر الخطوط الهندسية عمارة وادي مزاب وإيقاعه.","Las bandas geométricas recuerdan la arquitectura y el ritmo del valle del M’Zab."),artisanSlug:"maison-nahla",categorySlug:"textiles",region:text("Ghardaïa","Ghardaïa","غرداية","Ghardaïa"),materials:text("Local wool","Laine locale","صوف محلي","Lana local"),method:text("Handloom woven","Tissé sur métier manuel","منسوج على نول يدوي","Tejido en telar manual"),priceMinor:7800,previousPriceMinor:9200,currency:"EUR",availability:"in_stock",images:[image],featured:true,rating:4.8,reviewCount:17},
  { slug:"aures-painted-vessel",name:text("Aurès painted vessel","Vase peint des Aurès","إناء أوراسي مزخرف","Vasija pintada de Aurès"),summary:text("A sculptural clay vessel marked with restrained ancestral symbols.","Un vase sculptural marqué de symboles ancestraux sobres.","إناء طيني منحوت بعلامات تراثية هادئة.","Una vasija escultórica con sobrios símbolos ancestrales."),story:text("Built by hand without a wheel, then finished with mineral colour.","Monté à la main sans tour, puis fini avec des couleurs minérales.","مشكل باليد دون عجلة ومزين بألوان معدنية.","Hecho a mano sin torno y acabado con color mineral."),artisanSlug:"terre-des-aures",categorySlug:"pottery",region:text("Aurès","Aurès","الأوراس","Aurès"),materials:text("Local clay and mineral pigment","Argile locale et pigments minéraux","طين محلي وأصباغ معدنية","Arcilla local y pigmentos minerales"),method:text("Coiled and hand painted","Monté au colombin et peint à la main","بناء حلزوني ورسم يدوي","Modelado por rollos y pintado a mano"),priceMinor:9600,currency:"EUR",availability:"made_to_order",images:[image,image],featured:true,new:true,rating:4.7,reviewCount:11},
  { slug:"engraved-copper-tray",name:text("Engraved copper tray","Plateau en cuivre gravé","صينية نحاسية منقوشة","Bandeja de cobre grabada"),summary:text("A broad serving tray engraved in slow concentric rhythms.","Un grand plateau gravé de rythmes concentriques.","صينية واسعة منقوشة بإيقاعات دائرية.","Una amplia bandeja grabada con ritmos concéntricos."),story:text("Hammer marks remain visible as a record of the hand that shaped it.","Les traces du marteau restent visibles comme mémoire du geste.","تبقى آثار المطرقة شاهدة على اليد التي شكلتها.","Las marcas del martillo conservan la memoria de quien la formó."),artisanSlug:"atelier-tala",categorySlug:"metalwork",region:text("Algiers","Alger","الجزائر","Argel"),materials:text("Copper","Cuivre","نحاس","Cobre"),method:text("Hammered and engraved by hand","Martelé et gravé à la main","طرق ونقش يدوي","Martillado y grabado a mano"),priceMinor:14800,currency:"EUR",availability:"in_stock",images:[image],featured:true,rating:4.9,reviewCount:34},
  { slug:"halfa-market-basket",name:text("Halfa market basket","Panier de marché en halfa","سلة سوق من الحلفاء","Cesta de mercado de esparto"),summary:text("A strong everyday basket braided from sun-dried halfa.","Un panier quotidien robuste tressé en halfa séchée au soleil.","سلة يومية متينة مضفورة من الحلفاء المجففة.","Una cesta resistente trenzada con esparto secado al sol."),story:text("Its practical form is refined through balanced handles and natural fibre variation.","Sa forme pratique est affinée par des anses équilibrées et les variations de la fibre.","يتجمل شكلها العملي بمقابض متوازنة وتنوع الألياف الطبيعية.","Su forma práctica se refina con asas equilibradas y variación natural."),artisanSlug:"maison-nahla",categorySlug:"basketry",region:text("Djelfa","Djelfa","الجلفة","Djelfa"),materials:text("Halfa grass","Herbe halfa","عشب الحلفاء","Esparto"),method:text("Hand braided","Tressé à la main","مضفور يدوياً","Trenzado a mano"),priceMinor:5400,currency:"EUR",availability:"in_stock",images:[image],new:true,rating:4.6,reviewCount:9},
  { slug:"tooled-leather-journal",name:text("Tooled leather journal","Carnet en cuir repoussé","دفتر جلدي منقوش","Cuaderno de cuero repujado"),summary:text("A refillable journal wrapped in hand-tooled vegetable-tanned leather.","Un carnet rechargeable gainé de cuir tanné végétal repoussé à la main.","دفتر قابل للتعبئة بغلاف جلدي نباتي منقوش يدوياً.","Un cuaderno recargable envuelto en cuero vegetal labrado a mano."),story:text("The cover develops a deep patina while preserving the maker’s drawn geometry.","La couverture développe une patine profonde tout en gardant la géométrie du créateur.","يكتسب الغلاف عتيقة جميلة مع احتفاظه بزخرفة الصانع.","La cubierta desarrolla una pátina profunda conservando la geometría del artesano."),artisanSlug:"terre-des-aures",categorySlug:"leather",region:text("Tlemcen","Tlemcen","تلمسان","Tlemcen"),materials:text("Vegetable-tanned leather and paper","Cuir tanné végétal et papier","جلد مدبوغ نباتياً وورق","Cuero vegetal y papel"),method:text("Cut, stitched, and tooled by hand","Découpé, cousu et repoussé à la main","قص وخياطة ونقش يدوي","Cortado, cosido y labrado a mano"),priceMinor:6800,currency:"EUR",availability:"out_of_stock",images:[image],rating:4.8,reviewCount:13},
] satisfies Product[]).map((product) => ({ ...product, images: productImages[product.categorySlug] }));

export const orders: Order[] = [{ id:"AIS-2026-0148",placedAt:"2026-07-18",status:"shipped",items:[{productSlug:"kabyle-silver-brooch",quantity:1},{productSlug:"halfa-market-basket",quantity:1}],totalMinor:17900,currency:"EUR",address:{fullName:"Amel Benamar",email:"amel@example.com",phone:"+213 555 000 000",line1:"12 Rue des Oliviers",city:"Alger",postalCode:"16000",country:"Algeria"},trackingEvents:[{label:"Order confirmed",date:"18 July 2026",complete:true},{label:"Quality checked and packed",date:"20 July 2026",complete:true},{label:"Shipment handed over",date:"21 July 2026",complete:true},{label:"Delivered",date:"Pending",complete:false}]}];

export const getProduct=(slug:string)=>products.find((product)=>product.slug===slug);
export const getArtisan=(slug:string)=>artisans.find((artisan)=>artisan.slug===slug);
export const getCategory=(slug:string)=>categories.find((category)=>category.slug===slug);
export const getOrder=(id:string)=>orders.find((order)=>order.id===id);
