// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ArtisanDocument is an object representing the database table.
type ArtisanDocument struct {
	ID               string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	ArtisanProfileID string      `boil:"artisan_profile_id" json:"artisan_profile_id" toml:"artisan_profile_id" yaml:"artisan_profile_id"`
	DocumentType     string      `boil:"document_type" json:"document_type" toml:"document_type" yaml:"document_type"`
	ObjectKey        string      `boil:"object_key" json:"object_key" toml:"object_key" yaml:"object_key"`
	OriginalFilename null.String `boil:"original_filename" json:"original_filename,omitempty" toml:"original_filename" yaml:"original_filename,omitempty"`
	MediaType        string      `boil:"media_type" json:"media_type" toml:"media_type" yaml:"media_type"`
	SizeBytes        int64       `boil:"size_bytes" json:"size_bytes" toml:"size_bytes" yaml:"size_bytes"`
	ChecksumSha256   null.String `boil:"checksum_sha256" json:"checksum_sha256,omitempty" toml:"checksum_sha256" yaml:"checksum_sha256,omitempty"`
	CreatedAt        time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *artisanDocumentR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L artisanDocumentL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ArtisanDocumentColumns = struct {
	ID               string
	ArtisanProfileID string
	DocumentType     string
	ObjectKey        string
	OriginalFilename string
	MediaType        string
	SizeBytes        string
	ChecksumSha256   string
	CreatedAt        string
}{
	ID:               "id",
	ArtisanProfileID: "artisan_profile_id",
	DocumentType:     "document_type",
	ObjectKey:        "object_key",
	OriginalFilename: "original_filename",
	MediaType:        "media_type",
	SizeBytes:        "size_bytes",
	ChecksumSha256:   "checksum_sha256",
	CreatedAt:        "created_at",
}

var ArtisanDocumentTableColumns = struct {
	ID               string
	ArtisanProfileID string
	DocumentType     string
	ObjectKey        string
	OriginalFilename string
	MediaType        string
	SizeBytes        string
	ChecksumSha256   string
	CreatedAt        string
}{
	ID:               "artisan_documents.id",
	ArtisanProfileID: "artisan_documents.artisan_profile_id",
	DocumentType:     "artisan_documents.document_type",
	ObjectKey:        "artisan_documents.object_key",
	OriginalFilename: "artisan_documents.original_filename",
	MediaType:        "artisan_documents.media_type",
	SizeBytes:        "artisan_documents.size_bytes",
	ChecksumSha256:   "artisan_documents.checksum_sha256",
	CreatedAt:        "artisan_documents.created_at",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var ArtisanDocumentWhere = struct {
	ID               whereHelperstring
	ArtisanProfileID whereHelperstring
	DocumentType     whereHelperstring
	ObjectKey        whereHelperstring
	OriginalFilename whereHelpernull_String
	MediaType        whereHelperstring
	SizeBytes        whereHelperint64
	ChecksumSha256   whereHelpernull_String
	CreatedAt        whereHelpertime_Time
}{
	ID:               whereHelperstring{field: "\"artisan_documents\".\"id\""},
	ArtisanProfileID: whereHelperstring{field: "\"artisan_documents\".\"artisan_profile_id\""},
	DocumentType:     whereHelperstring{field: "\"artisan_documents\".\"document_type\""},
	ObjectKey:        whereHelperstring{field: "\"artisan_documents\".\"object_key\""},
	OriginalFilename: whereHelpernull_String{field: "\"artisan_documents\".\"original_filename\""},
	MediaType:        whereHelperstring{field: "\"artisan_documents\".\"media_type\""},
	SizeBytes:        whereHelperint64{field: "\"artisan_documents\".\"size_bytes\""},
	ChecksumSha256:   whereHelpernull_String{field: "\"artisan_documents\".\"checksum_sha256\""},
	CreatedAt:        whereHelpertime_Time{field: "\"artisan_documents\".\"created_at\""},
}

// ArtisanDocumentRels is where relationship names are stored.
var ArtisanDocumentRels = struct {
	ArtisanProfile string
}{
	ArtisanProfile: "ArtisanProfile",
}

// artisanDocumentR is where relationships are stored.
type artisanDocumentR struct {
	ArtisanProfile *ArtisanProfile `boil:"ArtisanProfile" json:"ArtisanProfile" toml:"ArtisanProfile" yaml:"ArtisanProfile"`
}

// NewStruct creates a new relationship struct
func (*artisanDocumentR) NewStruct() *artisanDocumentR {
	return &artisanDocumentR{}
}

func (o *ArtisanDocument) GetArtisanProfile() *ArtisanProfile {
	if o == nil {
		return nil
	}

	return o.R.GetArtisanProfile()
}

func (r *artisanDocumentR) GetArtisanProfile() *ArtisanProfile {
	if r == nil {
		return nil
	}

	return r.ArtisanProfile
}

// artisanDocumentL is where Load methods for each relationship are stored.
type artisanDocumentL struct{}

var (
	artisanDocumentAllColumns            = []string{"id", "artisan_profile_id", "document_type", "object_key", "original_filename", "media_type", "size_bytes", "checksum_sha256", "created_at"}
	artisanDocumentColumnsWithoutDefault = []string{"artisan_profile_id", "document_type", "object_key", "media_type", "size_bytes"}
	artisanDocumentColumnsWithDefault    = []string{"id", "original_filename", "checksum_sha256", "created_at"}
	artisanDocumentPrimaryKeyColumns     = []string{"id"}
	artisanDocumentGeneratedColumns      = []string{}
)

type (
	// ArtisanDocumentSlice is an alias for a slice of pointers to ArtisanDocument.
	// This should almost always be used instead of []ArtisanDocument.
	ArtisanDocumentSlice []*ArtisanDocument
	// ArtisanDocumentHook is the signature for custom ArtisanDocument hook methods
	ArtisanDocumentHook func(context.Context, boil.ContextExecutor, *ArtisanDocument) error

	artisanDocumentQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	artisanDocumentType                 = reflect.TypeOf(&ArtisanDocument{})
	artisanDocumentMapping              = queries.MakeStructMapping(artisanDocumentType)
	artisanDocumentPrimaryKeyMapping, _ = queries.BindMapping(artisanDocumentType, artisanDocumentMapping, artisanDocumentPrimaryKeyColumns)
	artisanDocumentInsertCacheMut       sync.RWMutex
	artisanDocumentInsertCache          = make(map[string]insertCache)
	artisanDocumentUpdateCacheMut       sync.RWMutex
	artisanDocumentUpdateCache          = make(map[string]updateCache)
	artisanDocumentUpsertCacheMut       sync.RWMutex
	artisanDocumentUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var artisanDocumentAfterSelectMu sync.Mutex
var artisanDocumentAfterSelectHooks []ArtisanDocumentHook

var artisanDocumentBeforeInsertMu sync.Mutex
var artisanDocumentBeforeInsertHooks []ArtisanDocumentHook
var artisanDocumentAfterInsertMu sync.Mutex
var artisanDocumentAfterInsertHooks []ArtisanDocumentHook

var artisanDocumentBeforeUpdateMu sync.Mutex
var artisanDocumentBeforeUpdateHooks []ArtisanDocumentHook
var artisanDocumentAfterUpdateMu sync.Mutex
var artisanDocumentAfterUpdateHooks []ArtisanDocumentHook

var artisanDocumentBeforeDeleteMu sync.Mutex
var artisanDocumentBeforeDeleteHooks []ArtisanDocumentHook
var artisanDocumentAfterDeleteMu sync.Mutex
var artisanDocumentAfterDeleteHooks []ArtisanDocumentHook

var artisanDocumentBeforeUpsertMu sync.Mutex
var artisanDocumentBeforeUpsertHooks []ArtisanDocumentHook
var artisanDocumentAfterUpsertMu sync.Mutex
var artisanDocumentAfterUpsertHooks []ArtisanDocumentHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ArtisanDocument) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanDocumentAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ArtisanDocument) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanDocumentBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ArtisanDocument) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanDocumentAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ArtisanDocument) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanDocumentBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ArtisanDocument) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanDocumentAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ArtisanDocument) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanDocumentBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ArtisanDocument) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanDocumentAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ArtisanDocument) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanDocumentBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ArtisanDocument) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanDocumentAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddArtisanDocumentHook registers your hook function for all future operations.
func AddArtisanDocumentHook(hookPoint boil.HookPoint, artisanDocumentHook ArtisanDocumentHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		artisanDocumentAfterSelectMu.Lock()
		artisanDocumentAfterSelectHooks = append(artisanDocumentAfterSelectHooks, artisanDocumentHook)
		artisanDocumentAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		artisanDocumentBeforeInsertMu.Lock()
		artisanDocumentBeforeInsertHooks = append(artisanDocumentBeforeInsertHooks, artisanDocumentHook)
		artisanDocumentBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		artisanDocumentAfterInsertMu.Lock()
		artisanDocumentAfterInsertHooks = append(artisanDocumentAfterInsertHooks, artisanDocumentHook)
		artisanDocumentAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		artisanDocumentBeforeUpdateMu.Lock()
		artisanDocumentBeforeUpdateHooks = append(artisanDocumentBeforeUpdateHooks, artisanDocumentHook)
		artisanDocumentBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		artisanDocumentAfterUpdateMu.Lock()
		artisanDocumentAfterUpdateHooks = append(artisanDocumentAfterUpdateHooks, artisanDocumentHook)
		artisanDocumentAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		artisanDocumentBeforeDeleteMu.Lock()
		artisanDocumentBeforeDeleteHooks = append(artisanDocumentBeforeDeleteHooks, artisanDocumentHook)
		artisanDocumentBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		artisanDocumentAfterDeleteMu.Lock()
		artisanDocumentAfterDeleteHooks = append(artisanDocumentAfterDeleteHooks, artisanDocumentHook)
		artisanDocumentAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		artisanDocumentBeforeUpsertMu.Lock()
		artisanDocumentBeforeUpsertHooks = append(artisanDocumentBeforeUpsertHooks, artisanDocumentHook)
		artisanDocumentBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		artisanDocumentAfterUpsertMu.Lock()
		artisanDocumentAfterUpsertHooks = append(artisanDocumentAfterUpsertHooks, artisanDocumentHook)
		artisanDocumentAfterUpsertMu.Unlock()
	}
}

// One returns a single artisanDocument record from the query.
func (q artisanDocumentQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ArtisanDocument, error) {
	o := &ArtisanDocument{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for artisan_documents")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ArtisanDocument records from the query.
func (q artisanDocumentQuery) All(ctx context.Context, exec boil.ContextExecutor) (ArtisanDocumentSlice, error) {
	var o []*ArtisanDocument

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ArtisanDocument slice")
	}

	if len(artisanDocumentAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ArtisanDocument records in the query.
func (q artisanDocumentQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count artisan_documents rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q artisanDocumentQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if artisan_documents exists")
	}

	return count > 0, nil
}

// ArtisanProfile pointed to by the foreign key.
func (o *ArtisanDocument) ArtisanProfile(mods ...qm.QueryMod) artisanProfileQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ArtisanProfileID),
	}

	queryMods = append(queryMods, mods...)

	return ArtisanProfiles(queryMods...)
}

// LoadArtisanProfile allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (artisanDocumentL) LoadArtisanProfile(ctx context.Context, e boil.ContextExecutor, singular bool, maybeArtisanDocument interface{}, mods queries.Applicator) error {
	var slice []*ArtisanDocument
	var object *ArtisanDocument

	if singular {
		var ok bool
		object, ok = maybeArtisanDocument.(*ArtisanDocument)
		if !ok {
			object = new(ArtisanDocument)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeArtisanDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeArtisanDocument))
			}
		}
	} else {
		s, ok := maybeArtisanDocument.(*[]*ArtisanDocument)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeArtisanDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeArtisanDocument))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &artisanDocumentR{}
		}
		args[object.ArtisanProfileID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &artisanDocumentR{}
			}

			args[obj.ArtisanProfileID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`artisan_profiles`),
		qm.WhereIn(`artisan_profiles.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ArtisanProfile")
	}

	var resultSlice []*ArtisanProfile
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ArtisanProfile")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for artisan_profiles")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for artisan_profiles")
	}

	if len(artisanProfileAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ArtisanProfile = foreign
		if foreign.R == nil {
			foreign.R = &artisanProfileR{}
		}
		foreign.R.ArtisanDocuments = append(foreign.R.ArtisanDocuments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ArtisanProfileID == foreign.ID {
				local.R.ArtisanProfile = foreign
				if foreign.R == nil {
					foreign.R = &artisanProfileR{}
				}
				foreign.R.ArtisanDocuments = append(foreign.R.ArtisanDocuments, local)
				break
			}
		}
	}

	return nil
}

// SetArtisanProfile of the artisanDocument to the related item.
// Sets o.R.ArtisanProfile to related.
// Adds o to related.R.ArtisanDocuments.
func (o *ArtisanDocument) SetArtisanProfile(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ArtisanProfile) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"artisan_documents\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"artisan_profile_id"}),
		strmangle.WhereClause("\"", "\"", 2, artisanDocumentPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ArtisanProfileID = related.ID
	if o.R == nil {
		o.R = &artisanDocumentR{
			ArtisanProfile: related,
		}
	} else {
		o.R.ArtisanProfile = related
	}

	if related.R == nil {
		related.R = &artisanProfileR{
			ArtisanDocuments: ArtisanDocumentSlice{o},
		}
	} else {
		related.R.ArtisanDocuments = append(related.R.ArtisanDocuments, o)
	}

	return nil
}

// ArtisanDocuments retrieves all the records using an executor.
func ArtisanDocuments(mods ...qm.QueryMod) artisanDocumentQuery {
	mods = append(mods, qm.From("\"artisan_documents\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"artisan_documents\".*"})
	}

	return artisanDocumentQuery{q}
}

// FindArtisanDocument retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindArtisanDocument(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*ArtisanDocument, error) {
	artisanDocumentObj := &ArtisanDocument{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"artisan_documents\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, artisanDocumentObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from artisan_documents")
	}

	if err = artisanDocumentObj.doAfterSelectHooks(ctx, exec); err != nil {
		return artisanDocumentObj, err
	}

	return artisanDocumentObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ArtisanDocument) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no artisan_documents provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(artisanDocumentColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	artisanDocumentInsertCacheMut.RLock()
	cache, cached := artisanDocumentInsertCache[key]
	artisanDocumentInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			artisanDocumentAllColumns,
			artisanDocumentColumnsWithDefault,
			artisanDocumentColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(artisanDocumentType, artisanDocumentMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(artisanDocumentType, artisanDocumentMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"artisan_documents\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"artisan_documents\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into artisan_documents")
	}

	if !cached {
		artisanDocumentInsertCacheMut.Lock()
		artisanDocumentInsertCache[key] = cache
		artisanDocumentInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ArtisanDocument.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ArtisanDocument) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	artisanDocumentUpdateCacheMut.RLock()
	cache, cached := artisanDocumentUpdateCache[key]
	artisanDocumentUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			artisanDocumentAllColumns,
			artisanDocumentPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update artisan_documents, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"artisan_documents\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, artisanDocumentPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(artisanDocumentType, artisanDocumentMapping, append(wl, artisanDocumentPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update artisan_documents row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for artisan_documents")
	}

	if !cached {
		artisanDocumentUpdateCacheMut.Lock()
		artisanDocumentUpdateCache[key] = cache
		artisanDocumentUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q artisanDocumentQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for artisan_documents")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for artisan_documents")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ArtisanDocumentSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), artisanDocumentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"artisan_documents\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, artisanDocumentPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in artisanDocument slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all artisanDocument")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ArtisanDocument) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no artisan_documents provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(artisanDocumentColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	artisanDocumentUpsertCacheMut.RLock()
	cache, cached := artisanDocumentUpsertCache[key]
	artisanDocumentUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			artisanDocumentAllColumns,
			artisanDocumentColumnsWithDefault,
			artisanDocumentColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			artisanDocumentAllColumns,
			artisanDocumentPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert artisan_documents, could not build update column list")
		}

		ret := strmangle.SetComplement(artisanDocumentAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(artisanDocumentPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert artisan_documents, could not build conflict column list")
			}

			conflict = make([]string, len(artisanDocumentPrimaryKeyColumns))
			copy(conflict, artisanDocumentPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"artisan_documents\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(artisanDocumentType, artisanDocumentMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(artisanDocumentType, artisanDocumentMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert artisan_documents")
	}

	if !cached {
		artisanDocumentUpsertCacheMut.Lock()
		artisanDocumentUpsertCache[key] = cache
		artisanDocumentUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ArtisanDocument record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ArtisanDocument) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ArtisanDocument provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), artisanDocumentPrimaryKeyMapping)
	sql := "DELETE FROM \"artisan_documents\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from artisan_documents")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for artisan_documents")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q artisanDocumentQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no artisanDocumentQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from artisan_documents")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for artisan_documents")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ArtisanDocumentSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(artisanDocumentBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), artisanDocumentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"artisan_documents\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, artisanDocumentPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from artisanDocument slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for artisan_documents")
	}

	if len(artisanDocumentAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ArtisanDocument) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindArtisanDocument(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ArtisanDocumentSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ArtisanDocumentSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), artisanDocumentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"artisan_documents\".* FROM \"artisan_documents\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, artisanDocumentPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ArtisanDocumentSlice")
	}

	*o = slice

	return nil
}

// ArtisanDocumentExists checks if the ArtisanDocument row exists.
func ArtisanDocumentExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"artisan_documents\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if artisan_documents exists")
	}

	return exists, nil
}

// Exists checks if the ArtisanDocument row exists.
func (o *ArtisanDocument) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ArtisanDocumentExists(ctx, exec, o.ID)
}
