// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// IdempotencyKey is an object representing the database table.
type IdempotencyKey struct {
	ID             string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	ActorUserID    null.String `boil:"actor_user_id" json:"actor_user_id,omitempty" toml:"actor_user_id" yaml:"actor_user_id,omitempty"`
	Scope          string      `boil:"scope" json:"scope" toml:"scope" yaml:"scope"`
	IdempotencyKey string      `boil:"idempotency_key" json:"idempotency_key" toml:"idempotency_key" yaml:"idempotency_key"`
	RequestHash    string      `boil:"request_hash" json:"request_hash" toml:"request_hash" yaml:"request_hash"`
	State          string      `boil:"state" json:"state" toml:"state" yaml:"state"`
	ResponseStatus null.Int    `boil:"response_status" json:"response_status,omitempty" toml:"response_status" yaml:"response_status,omitempty"`
	ResponseBody   null.JSON   `boil:"response_body" json:"response_body,omitempty" toml:"response_body" yaml:"response_body,omitempty"`
	ResourceType   null.String `boil:"resource_type" json:"resource_type,omitempty" toml:"resource_type" yaml:"resource_type,omitempty"`
	ResourceID     null.String `boil:"resource_id" json:"resource_id,omitempty" toml:"resource_id" yaml:"resource_id,omitempty"`
	CreatedAt      time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	ExpiresAt      time.Time   `boil:"expires_at" json:"expires_at" toml:"expires_at" yaml:"expires_at"`
	CompletedAt    null.Time   `boil:"completed_at" json:"completed_at,omitempty" toml:"completed_at" yaml:"completed_at,omitempty"`

	R *idempotencyKeyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L idempotencyKeyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var IdempotencyKeyColumns = struct {
	ID             string
	ActorUserID    string
	Scope          string
	IdempotencyKey string
	RequestHash    string
	State          string
	ResponseStatus string
	ResponseBody   string
	ResourceType   string
	ResourceID     string
	CreatedAt      string
	ExpiresAt      string
	CompletedAt    string
}{
	ID:             "id",
	ActorUserID:    "actor_user_id",
	Scope:          "scope",
	IdempotencyKey: "idempotency_key",
	RequestHash:    "request_hash",
	State:          "state",
	ResponseStatus: "response_status",
	ResponseBody:   "response_body",
	ResourceType:   "resource_type",
	ResourceID:     "resource_id",
	CreatedAt:      "created_at",
	ExpiresAt:      "expires_at",
	CompletedAt:    "completed_at",
}

var IdempotencyKeyTableColumns = struct {
	ID             string
	ActorUserID    string
	Scope          string
	IdempotencyKey string
	RequestHash    string
	State          string
	ResponseStatus string
	ResponseBody   string
	ResourceType   string
	ResourceID     string
	CreatedAt      string
	ExpiresAt      string
	CompletedAt    string
}{
	ID:             "idempotency_keys.id",
	ActorUserID:    "idempotency_keys.actor_user_id",
	Scope:          "idempotency_keys.scope",
	IdempotencyKey: "idempotency_keys.idempotency_key",
	RequestHash:    "idempotency_keys.request_hash",
	State:          "idempotency_keys.state",
	ResponseStatus: "idempotency_keys.response_status",
	ResponseBody:   "idempotency_keys.response_body",
	ResourceType:   "idempotency_keys.resource_type",
	ResourceID:     "idempotency_keys.resource_id",
	CreatedAt:      "idempotency_keys.created_at",
	ExpiresAt:      "idempotency_keys.expires_at",
	CompletedAt:    "idempotency_keys.completed_at",
}

// Generated where

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var IdempotencyKeyWhere = struct {
	ID             whereHelperstring
	ActorUserID    whereHelpernull_String
	Scope          whereHelperstring
	IdempotencyKey whereHelperstring
	RequestHash    whereHelperstring
	State          whereHelperstring
	ResponseStatus whereHelpernull_Int
	ResponseBody   whereHelpernull_JSON
	ResourceType   whereHelpernull_String
	ResourceID     whereHelpernull_String
	CreatedAt      whereHelpertime_Time
	ExpiresAt      whereHelpertime_Time
	CompletedAt    whereHelpernull_Time
}{
	ID:             whereHelperstring{field: "\"idempotency_keys\".\"id\""},
	ActorUserID:    whereHelpernull_String{field: "\"idempotency_keys\".\"actor_user_id\""},
	Scope:          whereHelperstring{field: "\"idempotency_keys\".\"scope\""},
	IdempotencyKey: whereHelperstring{field: "\"idempotency_keys\".\"idempotency_key\""},
	RequestHash:    whereHelperstring{field: "\"idempotency_keys\".\"request_hash\""},
	State:          whereHelperstring{field: "\"idempotency_keys\".\"state\""},
	ResponseStatus: whereHelpernull_Int{field: "\"idempotency_keys\".\"response_status\""},
	ResponseBody:   whereHelpernull_JSON{field: "\"idempotency_keys\".\"response_body\""},
	ResourceType:   whereHelpernull_String{field: "\"idempotency_keys\".\"resource_type\""},
	ResourceID:     whereHelpernull_String{field: "\"idempotency_keys\".\"resource_id\""},
	CreatedAt:      whereHelpertime_Time{field: "\"idempotency_keys\".\"created_at\""},
	ExpiresAt:      whereHelpertime_Time{field: "\"idempotency_keys\".\"expires_at\""},
	CompletedAt:    whereHelpernull_Time{field: "\"idempotency_keys\".\"completed_at\""},
}

// IdempotencyKeyRels is where relationship names are stored.
var IdempotencyKeyRels = struct {
	ActorUser string
}{
	ActorUser: "ActorUser",
}

// idempotencyKeyR is where relationships are stored.
type idempotencyKeyR struct {
	ActorUser *User `boil:"ActorUser" json:"ActorUser" toml:"ActorUser" yaml:"ActorUser"`
}

// NewStruct creates a new relationship struct
func (*idempotencyKeyR) NewStruct() *idempotencyKeyR {
	return &idempotencyKeyR{}
}

func (o *IdempotencyKey) GetActorUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetActorUser()
}

func (r *idempotencyKeyR) GetActorUser() *User {
	if r == nil {
		return nil
	}

	return r.ActorUser
}

// idempotencyKeyL is where Load methods for each relationship are stored.
type idempotencyKeyL struct{}

var (
	idempotencyKeyAllColumns            = []string{"id", "actor_user_id", "scope", "idempotency_key", "request_hash", "state", "response_status", "response_body", "resource_type", "resource_id", "created_at", "expires_at", "completed_at"}
	idempotencyKeyColumnsWithoutDefault = []string{"scope", "idempotency_key", "request_hash", "expires_at"}
	idempotencyKeyColumnsWithDefault    = []string{"id", "actor_user_id", "state", "response_status", "response_body", "resource_type", "resource_id", "created_at", "completed_at"}
	idempotencyKeyPrimaryKeyColumns     = []string{"id"}
	idempotencyKeyGeneratedColumns      = []string{}
)

type (
	// IdempotencyKeySlice is an alias for a slice of pointers to IdempotencyKey.
	// This should almost always be used instead of []IdempotencyKey.
	IdempotencyKeySlice []*IdempotencyKey
	// IdempotencyKeyHook is the signature for custom IdempotencyKey hook methods
	IdempotencyKeyHook func(context.Context, boil.ContextExecutor, *IdempotencyKey) error

	idempotencyKeyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	idempotencyKeyType                 = reflect.TypeOf(&IdempotencyKey{})
	idempotencyKeyMapping              = queries.MakeStructMapping(idempotencyKeyType)
	idempotencyKeyPrimaryKeyMapping, _ = queries.BindMapping(idempotencyKeyType, idempotencyKeyMapping, idempotencyKeyPrimaryKeyColumns)
	idempotencyKeyInsertCacheMut       sync.RWMutex
	idempotencyKeyInsertCache          = make(map[string]insertCache)
	idempotencyKeyUpdateCacheMut       sync.RWMutex
	idempotencyKeyUpdateCache          = make(map[string]updateCache)
	idempotencyKeyUpsertCacheMut       sync.RWMutex
	idempotencyKeyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var idempotencyKeyAfterSelectMu sync.Mutex
var idempotencyKeyAfterSelectHooks []IdempotencyKeyHook

var idempotencyKeyBeforeInsertMu sync.Mutex
var idempotencyKeyBeforeInsertHooks []IdempotencyKeyHook
var idempotencyKeyAfterInsertMu sync.Mutex
var idempotencyKeyAfterInsertHooks []IdempotencyKeyHook

var idempotencyKeyBeforeUpdateMu sync.Mutex
var idempotencyKeyBeforeUpdateHooks []IdempotencyKeyHook
var idempotencyKeyAfterUpdateMu sync.Mutex
var idempotencyKeyAfterUpdateHooks []IdempotencyKeyHook

var idempotencyKeyBeforeDeleteMu sync.Mutex
var idempotencyKeyBeforeDeleteHooks []IdempotencyKeyHook
var idempotencyKeyAfterDeleteMu sync.Mutex
var idempotencyKeyAfterDeleteHooks []IdempotencyKeyHook

var idempotencyKeyBeforeUpsertMu sync.Mutex
var idempotencyKeyBeforeUpsertHooks []IdempotencyKeyHook
var idempotencyKeyAfterUpsertMu sync.Mutex
var idempotencyKeyAfterUpsertHooks []IdempotencyKeyHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *IdempotencyKey) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range idempotencyKeyAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *IdempotencyKey) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range idempotencyKeyBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *IdempotencyKey) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range idempotencyKeyAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *IdempotencyKey) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range idempotencyKeyBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *IdempotencyKey) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range idempotencyKeyAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *IdempotencyKey) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range idempotencyKeyBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *IdempotencyKey) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range idempotencyKeyAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *IdempotencyKey) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range idempotencyKeyBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *IdempotencyKey) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range idempotencyKeyAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddIdempotencyKeyHook registers your hook function for all future operations.
func AddIdempotencyKeyHook(hookPoint boil.HookPoint, idempotencyKeyHook IdempotencyKeyHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		idempotencyKeyAfterSelectMu.Lock()
		idempotencyKeyAfterSelectHooks = append(idempotencyKeyAfterSelectHooks, idempotencyKeyHook)
		idempotencyKeyAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		idempotencyKeyBeforeInsertMu.Lock()
		idempotencyKeyBeforeInsertHooks = append(idempotencyKeyBeforeInsertHooks, idempotencyKeyHook)
		idempotencyKeyBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		idempotencyKeyAfterInsertMu.Lock()
		idempotencyKeyAfterInsertHooks = append(idempotencyKeyAfterInsertHooks, idempotencyKeyHook)
		idempotencyKeyAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		idempotencyKeyBeforeUpdateMu.Lock()
		idempotencyKeyBeforeUpdateHooks = append(idempotencyKeyBeforeUpdateHooks, idempotencyKeyHook)
		idempotencyKeyBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		idempotencyKeyAfterUpdateMu.Lock()
		idempotencyKeyAfterUpdateHooks = append(idempotencyKeyAfterUpdateHooks, idempotencyKeyHook)
		idempotencyKeyAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		idempotencyKeyBeforeDeleteMu.Lock()
		idempotencyKeyBeforeDeleteHooks = append(idempotencyKeyBeforeDeleteHooks, idempotencyKeyHook)
		idempotencyKeyBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		idempotencyKeyAfterDeleteMu.Lock()
		idempotencyKeyAfterDeleteHooks = append(idempotencyKeyAfterDeleteHooks, idempotencyKeyHook)
		idempotencyKeyAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		idempotencyKeyBeforeUpsertMu.Lock()
		idempotencyKeyBeforeUpsertHooks = append(idempotencyKeyBeforeUpsertHooks, idempotencyKeyHook)
		idempotencyKeyBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		idempotencyKeyAfterUpsertMu.Lock()
		idempotencyKeyAfterUpsertHooks = append(idempotencyKeyAfterUpsertHooks, idempotencyKeyHook)
		idempotencyKeyAfterUpsertMu.Unlock()
	}
}

// One returns a single idempotencyKey record from the query.
func (q idempotencyKeyQuery) One(ctx context.Context, exec boil.ContextExecutor) (*IdempotencyKey, error) {
	o := &IdempotencyKey{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for idempotency_keys")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all IdempotencyKey records from the query.
func (q idempotencyKeyQuery) All(ctx context.Context, exec boil.ContextExecutor) (IdempotencyKeySlice, error) {
	var o []*IdempotencyKey

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to IdempotencyKey slice")
	}

	if len(idempotencyKeyAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all IdempotencyKey records in the query.
func (q idempotencyKeyQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count idempotency_keys rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q idempotencyKeyQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if idempotency_keys exists")
	}

	return count > 0, nil
}

// ActorUser pointed to by the foreign key.
func (o *IdempotencyKey) ActorUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ActorUserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadActorUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (idempotencyKeyL) LoadActorUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeIdempotencyKey interface{}, mods queries.Applicator) error {
	var slice []*IdempotencyKey
	var object *IdempotencyKey

	if singular {
		var ok bool
		object, ok = maybeIdempotencyKey.(*IdempotencyKey)
		if !ok {
			object = new(IdempotencyKey)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeIdempotencyKey)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeIdempotencyKey))
			}
		}
	} else {
		s, ok := maybeIdempotencyKey.(*[]*IdempotencyKey)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeIdempotencyKey)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeIdempotencyKey))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &idempotencyKeyR{}
		}
		if !queries.IsNil(object.ActorUserID) {
			args[object.ActorUserID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &idempotencyKeyR{}
			}

			if !queries.IsNil(obj.ActorUserID) {
				args[obj.ActorUserID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ActorUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.ActorUserIdempotencyKeys = append(foreign.R.ActorUserIdempotencyKeys, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ActorUserID, foreign.ID) {
				local.R.ActorUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.ActorUserIdempotencyKeys = append(foreign.R.ActorUserIdempotencyKeys, local)
				break
			}
		}
	}

	return nil
}

// SetActorUser of the idempotencyKey to the related item.
// Sets o.R.ActorUser to related.
// Adds o to related.R.ActorUserIdempotencyKeys.
func (o *IdempotencyKey) SetActorUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"idempotency_keys\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"actor_user_id"}),
		strmangle.WhereClause("\"", "\"", 2, idempotencyKeyPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ActorUserID, related.ID)
	if o.R == nil {
		o.R = &idempotencyKeyR{
			ActorUser: related,
		}
	} else {
		o.R.ActorUser = related
	}

	if related.R == nil {
		related.R = &userR{
			ActorUserIdempotencyKeys: IdempotencyKeySlice{o},
		}
	} else {
		related.R.ActorUserIdempotencyKeys = append(related.R.ActorUserIdempotencyKeys, o)
	}

	return nil
}

// RemoveActorUser relationship.
// Sets o.R.ActorUser to nil.
// Removes o from all passed in related items' relationships struct.
func (o *IdempotencyKey) RemoveActorUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.ActorUserID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("actor_user_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.ActorUser = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.ActorUserIdempotencyKeys {
		if queries.Equal(o.ActorUserID, ri.ActorUserID) {
			continue
		}

		ln := len(related.R.ActorUserIdempotencyKeys)
		if ln > 1 && i < ln-1 {
			related.R.ActorUserIdempotencyKeys[i] = related.R.ActorUserIdempotencyKeys[ln-1]
		}
		related.R.ActorUserIdempotencyKeys = related.R.ActorUserIdempotencyKeys[:ln-1]
		break
	}
	return nil
}

// IdempotencyKeys retrieves all the records using an executor.
func IdempotencyKeys(mods ...qm.QueryMod) idempotencyKeyQuery {
	mods = append(mods, qm.From("\"idempotency_keys\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"idempotency_keys\".*"})
	}

	return idempotencyKeyQuery{q}
}

// FindIdempotencyKey retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindIdempotencyKey(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*IdempotencyKey, error) {
	idempotencyKeyObj := &IdempotencyKey{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"idempotency_keys\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, idempotencyKeyObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from idempotency_keys")
	}

	if err = idempotencyKeyObj.doAfterSelectHooks(ctx, exec); err != nil {
		return idempotencyKeyObj, err
	}

	return idempotencyKeyObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *IdempotencyKey) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no idempotency_keys provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(idempotencyKeyColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	idempotencyKeyInsertCacheMut.RLock()
	cache, cached := idempotencyKeyInsertCache[key]
	idempotencyKeyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			idempotencyKeyAllColumns,
			idempotencyKeyColumnsWithDefault,
			idempotencyKeyColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(idempotencyKeyType, idempotencyKeyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(idempotencyKeyType, idempotencyKeyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"idempotency_keys\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"idempotency_keys\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into idempotency_keys")
	}

	if !cached {
		idempotencyKeyInsertCacheMut.Lock()
		idempotencyKeyInsertCache[key] = cache
		idempotencyKeyInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the IdempotencyKey.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *IdempotencyKey) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	idempotencyKeyUpdateCacheMut.RLock()
	cache, cached := idempotencyKeyUpdateCache[key]
	idempotencyKeyUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			idempotencyKeyAllColumns,
			idempotencyKeyPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update idempotency_keys, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"idempotency_keys\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, idempotencyKeyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(idempotencyKeyType, idempotencyKeyMapping, append(wl, idempotencyKeyPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update idempotency_keys row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for idempotency_keys")
	}

	if !cached {
		idempotencyKeyUpdateCacheMut.Lock()
		idempotencyKeyUpdateCache[key] = cache
		idempotencyKeyUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q idempotencyKeyQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for idempotency_keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for idempotency_keys")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o IdempotencyKeySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), idempotencyKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"idempotency_keys\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, idempotencyKeyPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in idempotencyKey slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all idempotencyKey")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *IdempotencyKey) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no idempotency_keys provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(idempotencyKeyColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	idempotencyKeyUpsertCacheMut.RLock()
	cache, cached := idempotencyKeyUpsertCache[key]
	idempotencyKeyUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			idempotencyKeyAllColumns,
			idempotencyKeyColumnsWithDefault,
			idempotencyKeyColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			idempotencyKeyAllColumns,
			idempotencyKeyPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert idempotency_keys, could not build update column list")
		}

		ret := strmangle.SetComplement(idempotencyKeyAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(idempotencyKeyPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert idempotency_keys, could not build conflict column list")
			}

			conflict = make([]string, len(idempotencyKeyPrimaryKeyColumns))
			copy(conflict, idempotencyKeyPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"idempotency_keys\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(idempotencyKeyType, idempotencyKeyMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(idempotencyKeyType, idempotencyKeyMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert idempotency_keys")
	}

	if !cached {
		idempotencyKeyUpsertCacheMut.Lock()
		idempotencyKeyUpsertCache[key] = cache
		idempotencyKeyUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single IdempotencyKey record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *IdempotencyKey) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no IdempotencyKey provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), idempotencyKeyPrimaryKeyMapping)
	sql := "DELETE FROM \"idempotency_keys\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from idempotency_keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for idempotency_keys")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q idempotencyKeyQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no idempotencyKeyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from idempotency_keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for idempotency_keys")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o IdempotencyKeySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(idempotencyKeyBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), idempotencyKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"idempotency_keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, idempotencyKeyPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from idempotencyKey slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for idempotency_keys")
	}

	if len(idempotencyKeyAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *IdempotencyKey) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindIdempotencyKey(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *IdempotencyKeySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := IdempotencyKeySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), idempotencyKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"idempotency_keys\".* FROM \"idempotency_keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, idempotencyKeyPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in IdempotencyKeySlice")
	}

	*o = slice

	return nil
}

// IdempotencyKeyExists checks if the IdempotencyKey row exists.
func IdempotencyKeyExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"idempotency_keys\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if idempotency_keys exists")
	}

	return exists, nil
}

// Exists checks if the IdempotencyKey row exists.
func (o *IdempotencyKey) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return IdempotencyKeyExists(ctx, exec, o.ID)
}
