import type { Locale } from "./i18n";

const en = {
  shop: "Shop",
  products: "Products",
  artisans: "Artisans",
  search: "Search",
  cart: "Cart",
  checkout: "Checkout",
  account: "My account",
  orders: "Orders",
  login: "Sign in",
  register: "Create account",
  home: "Home",
  categories: "Categories",
  featured: "Selected treasures",
  featuredBody:
    "Objects chosen for their material integrity, cultural voice, and the hands behind them.",
  viewAll: "View all",
  newArrivals: "New arrivals",
  madeToOrder: "Made to order",
  madeToOrderBody:
    "Commission an object shaped around your story through a controlled request with the artisan.",
  discoverRegions: "Craft across Algeria",
  newsletter: "Letters from the workshop",
  newsletterBody: "Occasional stories, new objects, and meetings with makers.",
  email: "Email address",
  emailOrPhone: "Email or phone number",
  subscribe: "Subscribe",
  privacy: "By subscribing, you agree to receive AISHA editorial news.",
  filters: "Filters",
  sort: "Sort",
  featuredSort: "Featured",
  newest: "Newest",
  priceLow: "Price: low to high",
  priceHigh: "Price: high to low",
  availability: "Availability",
  inStock: "In stock",
  lowStock: "Only a few left",
  outOfStock: "Unavailable",
  availabilityPending: "Availability to be confirmed",
  available: "Available",
  apply: "Apply filters",
  clear: "Clear all",
  results: "objects",
  artisan: "Artisan",
  region: "Region",
  materials: "Materials",
  method: "Making method",
  story: "The story",
  quantity: "Quantity",
  addToCart: "Add to cart",
  buyNow: "Buy now",
  wishlist: "Save to wishlist",
  wishlistSignIn: "Sign in to save items to your wishlist.",
  wishlistError: "We could not update your wishlist. Please try again.",
  productUnavailable: "Product unavailable",
  related: "You may also like",
  quality: "Quality checked by AISHA",
  origin: "Made in Algeria",
  delivery: "Delivery options are confirmed during checkout.",
  shipping: "Shipping",
  continueShopping: "Continue shopping",
  emptyCart: "Your cart is waiting for its first object.",
  subtotal: "Provisional subtotal",
  total: "Total",
  promo: "Promotion code",
  remove: "Remove",
  summary: "Order summary",
  provisional:
    "Prices and availability are revalidated by the server at checkout.",
  contact: "Contact information",
  address: "Delivery address",
  shippingMethod: "Shipping method",
  paymentMethod: "Payment method",
  review: "Review",
  secureCheckout: "Secure checkout",
  placeOrder: "Review order",
  fullName: "Full name",
  phone: "Phone",
  line1: "Address",
  line2: "Apartment or suite (optional)",
  city: "City",
  postalCode: "Postal code",
  country: "Country",
  required: "This field is required.",
  paymentPending:
    "Payment method will be provided by the secure backend checkout.",
  shippingPending:
    "Eligible delivery methods and prices will be returned by the backend.",
  password: "Password",
  confirmPassword: "Confirm password",
  terms: "I accept the terms and privacy notice",
  forgot: "Forgot password?",
  noAccount: "New to AISHA?",
  hasAccount: "Already have an account?",
  overview: "Overview",
  profile: "Profile",
  addresses: "Addresses",
  purchases: "My purchases",
  artisanArea: "Artisan area",
  customerArea: "Customer account",
  manageWorkshops: "Manage workshops",
  becomeArtisan: "Become an artisan",
  artisanPending: "Artisan application pending",
  artisanSuspended: "Artisan selling is suspended",
  security: "Security",
  logout: "Sign out",
  welcome: "Welcome back",
  orderHistory: "Order history",
  order: "Order",
  date: "Date",
  status: "Status",
  track: "Track order",
  cancelOrder: "Cancel order",
  processing: "Processing",
  shipped: "Shipped",
  delivered: "Delivered",
  paymentStatus: "Payment status",
  fulfilment: "Fulfilment",
  tracking: "Tracking",
  support: "Contact support",
  invoice: "Download invoice",
  artisanDirectory: "Meet the makers",
  artisanDirectoryBody:
    "Discover the people, workshops, and regional languages behind AISHA objects.",
  craft: "Craft",
  verified: "Verified artisan",
  workshop: "Workshop",
  collection: "Collection",
  noResults: "No objects match your search.",
  tryAgain: "Adjust or clear the filters to continue discovering.",
  loadMore: "Load more",
  searchTitle: "Search AISHA",
  searchHint: "Search objects, artisans, regions, and materials",
  popular: "Popular searches",
  searchResults: "Search results",
  cartUpdated: "Cart updated",
  success: "Order received",
  successBody:
    "Your request has been prepared for secure backend confirmation.",
  backToCart: "Return to cart",
  menu: "Menu",
  close: "Close",
  previous: "Previous",
  next: "Next",
  share: "Share",
  zoomImage: "Enlarge image",
  ratingLabel: "out of 5 stars",
  activeFilters: "Active filters",
  category: "Category",
  price: "Price",
  allArtisans: "All artisans",
  allCategories: "All categories",
  trustOrigin: "Verified Algerian origin",
  trustQuality: "Quality inspected",
  trustPartnership: "Fair artisan partnership",
  trustDelivery: "Secure international delivery",
  artisanStory: "Hands behind every object",
  exploreArtisan: "Explore the workshop",
  promotional: "Made for you, made with time",
  emptyOrders: "No orders yet",
  emptyOrdersBody:
    "Your order history will appear here after a completed checkout.",
  accountStatus: "Account status",
  customerAccess: "Customer access",
  artisanAccess: "Artisan access",
  active: "Active",
  suspended: "Suspended",
  pending: "Pending",
  notStarted: "Not started",
  enabled: "Enabled",
  disabled: "Unavailable",
  accountLoading: "Loading your account…",
  accountUnavailable: "Your account is unavailable.",
  accountErrorBody: "We could not load the latest account state. Please try again.",
  emptyAddresses: "No saved addresses yet",
  emptyAddressesBody: "Add a delivery address so checkout can be completed faster.",
  viewOrders: "View orders",
  viewOrdersBody: "Your order history and tracking will appear here after checkout.",
  viewAddresses: "Manage addresses",
  viewAddressesBody: "Keep your delivery details ready for a future order.",
  notFound: "We could not find this page.",
  returnHome: "Return home",
  errorTitle: "Something interrupted this page.",
  errorBody: "Please try again. Your browsing session has been preserved.",
  retry: "Try again",
};
export type StoreCopy = { [K in keyof typeof en]: string };
const fr: StoreCopy = {
  ...en,
  shop: "Boutique",
  products: "Produits",
  artisans: "Artisans",
  search: "Rechercher",
  cart: "Panier",
  checkout: "Paiement",
  account: "Mon compte",
  orders: "Commandes",
  cancelOrder: "Annuler la commande",
  login: "Se connecter",
  register: "Créer un compte",
  home: "Accueil",
  categories: "Catégories",
  featured: "Trésors sélectionnés",
  viewAll: "Tout voir",
  newArrivals: "Nouveautés",
  madeToOrder: "Sur commande",
  filters: "Filtres",
  sort: "Trier",
  availability: "Disponibilité",
  inStock: "En stock",
  lowStock: "Plus que quelques pièces",
  outOfStock: "Indisponible",
  availabilityPending: "Disponibilité à confirmer",
  available: "Disponible",
  clear: "Tout effacer",
  artisan: "Artisan",
  region: "Région",
  materials: "Matières",
  method: "Méthode de fabrication",
  story: "L’histoire",
  quantity: "Quantité",
  addToCart: "Ajouter au panier",
  buyNow: "Acheter",
  wishlist: "Ajouter aux favoris",
  wishlistSignIn: "Connectez-vous pour enregistrer des articles dans vos favoris.",
  wishlistError: "Impossible de mettre à jour vos favoris. Réessayez.",
  productUnavailable: "Produit indisponible",
  related: "Vous aimerez aussi",
  continueShopping: "Continuer mes achats",
  subtotal: "Sous-total provisoire",
  total: "Total",
  remove: "Retirer",
  summary: "Récapitulatif",
  contact: "Coordonnées",
  address: "Adresse de livraison",
  shippingMethod: "Mode de livraison",
  paymentMethod: "Mode de paiement",
  review: "Vérification",
  secureCheckout: "Paiement sécurisé",
  placeOrder: "Vérifier la commande",
  fullName: "Nom complet",
  phone: "Téléphone",
  line1: "Adresse",
  city: "Ville",
  postalCode: "Code postal",
  country: "Pays",
  password: "Mot de passe",
  confirmPassword: "Confirmer le mot de passe",
  terms: "J’accepte les conditions et la notice de confidentialité",
  forgot: "Mot de passe oublié ?",
  overview: "Aperçu",
  profile: "Profil",
  addresses: "Adresses",
  purchases: "Mes achats",
  artisanArea: "Espace artisan",
  customerArea: "Compte client",
  manageWorkshops: "Gérer les ateliers",
  becomeArtisan: "Devenir artisan",
  artisanPending: "Demande artisan en cours",
  artisanSuspended: "La vente artisanale est suspendue",
  security: "Sécurité",
  logout: "Déconnexion",
  welcome: "Bon retour",
  orderHistory: "Historique des commandes",
  order: "Commande",
  date: "Date",
  status: "Statut",
  track: "Suivre",
  processing: "En préparation",
  shipped: "Expédiée",
  delivered: "Livrée",
  tracking: "Suivi",
  artisanDirectory: "Rencontrez les créateurs",
  craft: "Métier",
  verified: "Artisan vérifié",
  workshop: "Atelier",
  collection: "Collection",
  noResults: "Aucun objet ne correspond à votre recherche.",
  loadMore: "Voir plus",
  searchTitle: "Rechercher sur AISHA",
  searchResults: "Résultats",
  menu: "Menu",
  close: "Fermer",
  category: "Catégorie",
  price: "Prix",
  notFound: "Cette page est introuvable.",
  returnHome: "Retour à l’accueil",
};
const ar: StoreCopy = {
  ...en,
  shop: "المتجر",
  products: "المنتجات",
  artisans: "الحرفيون",
  search: "بحث",
  cart: "السلة",
  checkout: "الدفع",
  account: "حسابي",
  orders: "الطلبات",
  cancelOrder: "إلغاء الطلب",
  login: "تسجيل الدخول",
  register: "إنشاء حساب",
  home: "الرئيسية",
  categories: "الفئات",
  featured: "كنوز مختارة",
  viewAll: "عرض الكل",
  newArrivals: "وصل حديثاً",
  madeToOrder: "حسب الطلب",
  filters: "الفلاتر",
  sort: "الترتيب",
  availability: "التوفر",
  inStock: "متوفر",
  lowStock: "بقي القليل",
  outOfStock: "غير متوفر",
  availabilityPending: "سيتم تأكيد التوفر",
  available: "الكمية المتاحة",
  clear: "مسح الكل",
  artisan: "الحرفي",
  region: "المنطقة",
  materials: "المواد",
  method: "طريقة الصنع",
  story: "الحكاية",
  quantity: "الكمية",
  addToCart: "أضف إلى السلة",
  buyNow: "اشتر الآن",
  wishlist: "احفظ في المفضلة",
  wishlistSignIn: "سجّل الدخول لحفظ المنتجات في المفضلة.",
  wishlistError: "تعذر تحديث المفضلة. يرجى المحاولة مرة أخرى.",
  productUnavailable: "المنتج غير متاح",
  related: "قد يعجبك أيضاً",
  continueShopping: "متابعة التسوق",
  subtotal: "المجموع المؤقت",
  total: "المجموع",
  remove: "حذف",
  summary: "ملخص الطلب",
  contact: "معلومات الاتصال",
  address: "عنوان التوصيل",
  shippingMethod: "طريقة التوصيل",
  paymentMethod: "طريقة الدفع",
  review: "المراجعة",
  secureCheckout: "دفع آمن",
  placeOrder: "راجع الطلب",
  fullName: "الاسم الكامل",
  phone: "الهاتف",
  line1: "العنوان",
  city: "المدينة",
  postalCode: "الرمز البريدي",
  country: "البلد",
  password: "كلمة المرور",
  confirmPassword: "تأكيد كلمة المرور",
  terms: "أوافق على الشروط وإشعار الخصوصية",
  forgot: "نسيت كلمة المرور؟",
  overview: "نظرة عامة",
  profile: "الملف الشخصي",
  addresses: "العناوين",
  purchases: "مشترياتي",
  artisanArea: "مساحة الحرفي",
  customerArea: "حساب العميل",
  manageWorkshops: "إدارة الورشات",
  becomeArtisan: "كن حرفياً",
  artisanPending: "طلب الحرفي قيد المراجعة",
  artisanSuspended: "تم تعليق البيع كحرفي",
  security: "الأمان",
  logout: "تسجيل الخروج",
  welcome: "مرحباً بعودتك",
  orderHistory: "سجل الطلبات",
  order: "الطلب",
  date: "التاريخ",
  status: "الحالة",
  track: "تتبع الطلب",
  processing: "قيد التحضير",
  shipped: "تم الشحن",
  delivered: "تم التوصيل",
  tracking: "التتبع",
  artisanDirectory: "تعرّف على الصنّاع",
  craft: "الحرفة",
  verified: "حرفي موثّق",
  workshop: "الورشة",
  collection: "المجموعة",
  noResults: "لا توجد قطع تطابق بحثك.",
  loadMore: "عرض المزيد",
  searchTitle: "ابحث في عائشة",
  searchResults: "نتائج البحث",
  menu: "القائمة",
  close: "إغلاق",
  category: "الفئة",
  price: "السعر",
  notFound: "لم نعثر على هذه الصفحة.",
  returnHome: "العودة للرئيسية",
};
const es: StoreCopy = {
  ...en,
  shop: "Tienda",
  products: "Productos",
  artisans: "Artesanos",
  search: "Buscar",
  cart: "Cesta",
  checkout: "Pago",
  account: "Mi cuenta",
  orders: "Pedidos",
  cancelOrder: "Cancelar pedido",
  login: "Iniciar sesión",
  register: "Crear cuenta",
  home: "Inicio",
  categories: "Categorías",
  featured: "Tesoros seleccionados",
  viewAll: "Ver todo",
  newArrivals: "Novedades",
  madeToOrder: "Por encargo",
  filters: "Filtros",
  sort: "Ordenar",
  availability: "Disponibilidad",
  inStock: "Disponible",
  lowStock: "Quedan pocas piezas",
  outOfStock: "No disponible",
  availabilityPending: "Disponibilidad por confirmar",
  available: "Disponible",
  clear: "Borrar todo",
  artisan: "Artesano",
  region: "Región",
  materials: "Materiales",
  method: "Método de elaboración",
  story: "La historia",
  quantity: "Cantidad",
  addToCart: "Añadir a la cesta",
  buyNow: "Comprar ahora",
  wishlist: "Guardar en favoritos",
  wishlistSignIn: "Inicia sesión para guardar productos en favoritos.",
  wishlistError: "No se pudo actualizar favoritos. Inténtalo de nuevo.",
  productUnavailable: "Producto no disponible",
  related: "También te puede gustar",
  continueShopping: "Seguir comprando",
  subtotal: "Subtotal provisional",
  total: "Total",
  remove: "Eliminar",
  summary: "Resumen",
  contact: "Información de contacto",
  address: "Dirección de entrega",
  shippingMethod: "Método de envío",
  paymentMethod: "Método de pago",
  review: "Revisión",
  secureCheckout: "Pago seguro",
  placeOrder: "Revisar pedido",
  fullName: "Nombre completo",
  phone: "Teléfono",
  line1: "Dirección",
  city: "Ciudad",
  postalCode: "Código postal",
  country: "País",
  password: "Contraseña",
  confirmPassword: "Confirmar contraseña",
  terms: "Acepto los términos y el aviso de privacidad",
  forgot: "¿Olvidaste tu contraseña?",
  overview: "Resumen",
  profile: "Perfil",
  addresses: "Direcciones",
  purchases: "Mis compras",
  artisanArea: "Espacio del artesano",
  customerArea: "Cuenta del cliente",
  manageWorkshops: "Gestionar talleres",
  becomeArtisan: "Ser artesano",
  artisanPending: "Solicitud de artesano pendiente",
  artisanSuspended: "La venta artesanal está suspendida",
  security: "Seguridad",
  logout: "Cerrar sesión",
  welcome: "Bienvenido de nuevo",
  orderHistory: "Historial de pedidos",
  order: "Pedido",
  date: "Fecha",
  status: "Estado",
  track: "Seguir pedido",
  processing: "Procesando",
  shipped: "Enviado",
  delivered: "Entregado",
  tracking: "Seguimiento",
  artisanDirectory: "Conoce a los creadores",
  craft: "Oficio",
  verified: "Artesano verificado",
  workshop: "Taller",
  collection: "Colección",
  noResults: "Ningún objeto coincide con tu búsqueda.",
  loadMore: "Ver más",
  searchTitle: "Buscar en AISHA",
  searchResults: "Resultados",
  menu: "Menú",
  close: "Cerrar",
  category: "Categoría",
  price: "Precio",
  notFound: "No encontramos esta página.",
  returnHome: "Volver al inicio",
};
const publicOverrides = {
  fr: {
    featuredBody:
      "Des objets choisis pour l’intégrité de leurs matières, leur voix culturelle et les mains qui les façonnent.",
    madeToOrderBody:
      "Commandez une pièce façonnée autour de votre histoire grâce à une demande encadrée auprès de l’artisan.",
    discoverRegions: "Les savoir-faire d’Algérie",
    newsletter: "Lettres de l’atelier",
    newsletterBody:
      "Des histoires, de nouveaux objets et des rencontres avec les créateurs, occasionnellement.",
    email: "Adresse e-mail",
    emailOrPhone: "E-mail ou numéro de téléphone",
    subscribe: "S’abonner",
    privacy:
      "En vous abonnant, vous acceptez de recevoir les nouvelles éditoriales d’AISHA.",
    featuredSort: "Sélection",
    newest: "Plus récents",
    priceLow: "Prix croissant",
    priceHigh: "Prix décroissant",
    apply: "Appliquer les filtres",
    results: "objets",
    tryAgain:
      "Modifiez ou effacez les filtres pour poursuivre votre découverte.",
    searchHint: "Rechercher des objets, artisans, régions et matières",
    popular: "Recherches populaires",
    previous: "Précédent",
    next: "Suivant",
    activeFilters: "Filtres actifs",
    allArtisans: "Tous les artisans",
    allCategories: "Toutes les catégories",
    trustOrigin: "Origine algérienne vérifiée",
    trustQuality: "Qualité inspectée",
    trustPartnership: "Partenariat équitable avec les artisans",
    trustDelivery: "Livraison internationale sécurisée",
    artisanStory: "Les mains derrière chaque objet",
    exploreArtisan: "Découvrir l’atelier",
    promotional: "Fait pour vous, façonné avec le temps",
    quality: "Qualité contrôlée par AISHA",
    origin: "Fabriqué en Algérie",
    delivery: "Les options de livraison sont confirmées lors du paiement.",
    shipping: "Livraison",
    close: "Fermer",
    searchResults: "Résultats de recherche",
    accountStatus: "État du compte", customerAccess: "Accès client", artisanAccess: "Accès artisan", active: "Actif", suspended: "Suspendu", pending: "En attente", notStarted: "Non commencé", enabled: "Disponible", disabled: "Indisponible", accountLoading: "Chargement de votre compte…", accountUnavailable: "Votre compte est indisponible.", accountErrorBody: "Impossible de charger l’état du compte. Réessayez.", emptyAddresses: "Aucune adresse enregistrée", emptyAddressesBody: "Ajoutez une adresse de livraison pour faciliter vos prochaines commandes.", viewOrders: "Voir les commandes", viewOrdersBody: "Votre historique et votre suivi apparaîtront après le paiement.", viewAddresses: "Gérer les adresses", viewAddressesBody: "Conservez vos coordonnées de livraison pour une prochaine commande.", share: "Partager", zoomImage: "Agrandir l’image", ratingLabel: "sur 5 étoiles", errorTitle: "Cette page a rencontré un problème.", errorBody: "Veuillez réessayer. Votre navigation a été conservée.", retry: "Réessayer",
  },
  ar: {
    featuredBody:
      "قطع مختارة لنزاهة موادها وصوتها الثقافي والأيدي التي صنعتها.",
    madeToOrderBody: "اطلب قطعة تُصاغ حول حكايتك من خلال طلب منظم مع الحرفي.",
    discoverRegions: "حرف من أنحاء الجزائر",
    newsletter: "رسائل من الورشة",
    newsletterBody: "حكايات وقطع جديدة ولقاءات مع الصنّاع من حين لآخر.",
    email: "البريد الإلكتروني",
    emailOrPhone: "البريد الإلكتروني أو رقم الهاتف",
    subscribe: "اشترك",
    privacy: "بالاشتراك، توافق على تلقي أخبار عائشة التحريرية.",
    featuredSort: "مختارات",
    newest: "الأحدث",
    priceLow: "السعر: من الأقل إلى الأعلى",
    priceHigh: "السعر: من الأعلى إلى الأقل",
    apply: "تطبيق الفلاتر",
    results: "قطع",
    tryAgain: "عدّل الفلاتر أو امسحها لمواصلة الاكتشاف.",
    searchHint: "ابحث عن القطع والحرفيين والمناطق والمواد",
    popular: "عمليات بحث شائعة",
    previous: "السابق",
    next: "التالي",
    activeFilters: "الفلاتر النشطة",
    allArtisans: "كل الحرفيين",
    allCategories: "كل الفئات",
    trustOrigin: "أصل جزائري موثّق",
    trustQuality: "جودة مفحوصة",
    trustPartnership: "شراكة عادلة مع الحرفي",
    trustDelivery: "توصيل دولي آمن",
    artisanStory: "الأيدي وراء كل قطعة",
    exploreArtisan: "اكتشف الورشة",
    promotional: "مصنوع لك، وبعناية الوقت",
    quality: "جودة مفحوصة من عائشة",
    origin: "صُنع في الجزائر",
    delivery: "يتم تأكيد خيارات التوصيل أثناء إتمام الطلب.",
    shipping: "التوصيل",
    close: "إغلاق",
    searchResults: "نتائج البحث",
    accountStatus: "حالة الحساب", customerAccess: "وصول العميل", artisanAccess: "وصول الحرفي", active: "نشط", suspended: "معلّق", pending: "قيد الانتظار", notStarted: "لم يبدأ", enabled: "متاح", disabled: "غير متاح", accountLoading: "جارٍ تحميل حسابك…", accountUnavailable: "حسابك غير متاح.", accountErrorBody: "تعذر تحميل حالة الحساب الأخيرة. حاول مجددًا.", emptyAddresses: "لا توجد عناوين محفوظة", emptyAddressesBody: "أضف عنوان توصيل لتسهيل طلبك القادم.", viewOrders: "عرض الطلبات", viewOrdersBody: "سيظهر سجل الطلبات والتتبع بعد إتمام الطلب.", viewAddresses: "إدارة العناوين", viewAddressesBody: "احتفظ ببيانات التوصيل لطلب قادم.", share: "مشاركة", zoomImage: "تكبير الصورة", ratingLabel: "من 5 نجوم", errorTitle: "حدث عطل أثناء عرض هذه الصفحة.", errorBody: "يرجى المحاولة مجددًا. تم الاحتفاظ بجلسة التصفح.", retry: "حاول مجددًا",
  },
  es: {
    featuredBody:
      "Objetos elegidos por la integridad de sus materiales, su voz cultural y las manos que los crean.",
    madeToOrderBody:
      "Encarga una pieza creada en torno a tu historia mediante una solicitud guiada con el artesano.",
    discoverRegions: "Artesanía de toda Argelia",
    newsletter: "Cartas desde el taller",
    newsletterBody:
      "Historias ocasionales, nuevos objetos y encuentros con sus creadores.",
    email: "Correo electrónico",
    emailOrPhone: "Correo electrónico o número de teléfono",
    subscribe: "Suscribirse",
    privacy: "Al suscribirte, aceptas recibir noticias editoriales de AISHA.",
    featuredSort: "Destacados",
    newest: "Más recientes",
    priceLow: "Precio: de menor a mayor",
    priceHigh: "Precio: de mayor a menor",
    apply: "Aplicar filtros",
    results: "objetos",
    tryAgain: "Ajusta o borra los filtros para seguir descubriendo.",
    searchHint: "Buscar objetos, artesanos, regiones y materiales",
    popular: "Búsquedas populares",
    previous: "Anterior",
    next: "Siguiente",
    activeFilters: "Filtros activos",
    allArtisans: "Todos los artesanos",
    allCategories: "Todas las categorías",
    trustOrigin: "Origen argelino verificado",
    trustQuality: "Calidad inspeccionada",
    trustPartnership: "Colaboración artesanal justa",
    trustDelivery: "Entrega internacional segura",
    artisanStory: "Las manos detrás de cada objeto",
    exploreArtisan: "Descubrir el taller",
    promotional: "Hecho para ti, creado con tiempo",
    quality: "Calidad revisada por AISHA",
    origin: "Hecho en Argelia",
    delivery: "Las opciones de entrega se confirman durante el pago.",
    shipping: "Envío",
    close: "Cerrar",
    searchResults: "Resultados de búsqueda",
    accountStatus: "Estado de la cuenta", customerAccess: "Acceso de cliente", artisanAccess: "Acceso de artesano", active: "Activo", suspended: "Suspendido", pending: "Pendiente", notStarted: "No iniciado", enabled: "Disponible", disabled: "No disponible", accountLoading: "Cargando tu cuenta…", accountUnavailable: "Tu cuenta no está disponible.", accountErrorBody: "No pudimos cargar el estado actualizado de la cuenta. Inténtalo de nuevo.", emptyAddresses: "Aún no hay direcciones guardadas", emptyAddressesBody: "Añade una dirección de entrega para agilizar tu próximo pedido.", viewOrders: "Ver pedidos", viewOrdersBody: "Tu historial y seguimiento aparecerán después del pago.", viewAddresses: "Gestionar direcciones", viewAddressesBody: "Guarda tus datos de entrega para un próximo pedido.", share: "Compartir", zoomImage: "Ampliar imagen", ratingLabel: "de 5 estrellas", errorTitle: "Algo interrumpió esta página.", errorBody: "Inténtalo de nuevo. Tu sesión de navegación se ha conservado.", retry: "Intentar de nuevo",
  },
} satisfies Record<Exclude<Locale, "en">, Partial<StoreCopy>>;
const copies = {
  en,
  fr: { ...fr, ...publicOverrides.fr },
  ar: { ...ar, ...publicOverrides.ar },
  es: { ...es, ...publicOverrides.es },
};
export function storeCopy(locale: Locale) {
  return copies[locale];
}
