// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/aisha-platform/aisha/backend/internal/platform/config"
	"github.com/aisha-platform/aisha/backend/internal/platform/httpapi"
)

// Injectors from wire.go:

func initializeAPI(contextContext context.Context, configConfig config.Config) (*httpapi.Runtime, error) {
	runtime, err := httpapi.NewRuntime(contextContext, configConfig)
	if err != nil {
		return nil, err
	}
	return runtime, nil
}
