// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ArtisanMedium is an object representing the database table.
type ArtisanMedium struct {
	ID               string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	ArtisanProfileID string      `boil:"artisan_profile_id" json:"artisan_profile_id" toml:"artisan_profile_id" yaml:"artisan_profile_id"`
	MediaKind        string      `boil:"media_kind" json:"media_kind" toml:"media_kind" yaml:"media_kind"`
	ObjectKey        string      `boil:"object_key" json:"object_key" toml:"object_key" yaml:"object_key"`
	OriginalFilename null.String `boil:"original_filename" json:"original_filename,omitempty" toml:"original_filename" yaml:"original_filename,omitempty"`
	MediaType        string      `boil:"media_type" json:"media_type" toml:"media_type" yaml:"media_type"`
	SizeBytes        int64       `boil:"size_bytes" json:"size_bytes" toml:"size_bytes" yaml:"size_bytes"`
	ChecksumSha256   null.String `boil:"checksum_sha256" json:"checksum_sha256,omitempty" toml:"checksum_sha256" yaml:"checksum_sha256,omitempty"`
	SortOrder        int         `boil:"sort_order" json:"sort_order" toml:"sort_order" yaml:"sort_order"`
	Visibility       string      `boil:"visibility" json:"visibility" toml:"visibility" yaml:"visibility"`
	CreatedAt        time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *artisanMediumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L artisanMediumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ArtisanMediumColumns = struct {
	ID               string
	ArtisanProfileID string
	MediaKind        string
	ObjectKey        string
	OriginalFilename string
	MediaType        string
	SizeBytes        string
	ChecksumSha256   string
	SortOrder        string
	Visibility       string
	CreatedAt        string
}{
	ID:               "id",
	ArtisanProfileID: "artisan_profile_id",
	MediaKind:        "media_kind",
	ObjectKey:        "object_key",
	OriginalFilename: "original_filename",
	MediaType:        "media_type",
	SizeBytes:        "size_bytes",
	ChecksumSha256:   "checksum_sha256",
	SortOrder:        "sort_order",
	Visibility:       "visibility",
	CreatedAt:        "created_at",
}

var ArtisanMediumTableColumns = struct {
	ID               string
	ArtisanProfileID string
	MediaKind        string
	ObjectKey        string
	OriginalFilename string
	MediaType        string
	SizeBytes        string
	ChecksumSha256   string
	SortOrder        string
	Visibility       string
	CreatedAt        string
}{
	ID:               "artisan_media.id",
	ArtisanProfileID: "artisan_media.artisan_profile_id",
	MediaKind:        "artisan_media.media_kind",
	ObjectKey:        "artisan_media.object_key",
	OriginalFilename: "artisan_media.original_filename",
	MediaType:        "artisan_media.media_type",
	SizeBytes:        "artisan_media.size_bytes",
	ChecksumSha256:   "artisan_media.checksum_sha256",
	SortOrder:        "artisan_media.sort_order",
	Visibility:       "artisan_media.visibility",
	CreatedAt:        "artisan_media.created_at",
}

// Generated where

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var ArtisanMediumWhere = struct {
	ID               whereHelperstring
	ArtisanProfileID whereHelperstring
	MediaKind        whereHelperstring
	ObjectKey        whereHelperstring
	OriginalFilename whereHelpernull_String
	MediaType        whereHelperstring
	SizeBytes        whereHelperint64
	ChecksumSha256   whereHelpernull_String
	SortOrder        whereHelperint
	Visibility       whereHelperstring
	CreatedAt        whereHelpertime_Time
}{
	ID:               whereHelperstring{field: "\"artisan_media\".\"id\""},
	ArtisanProfileID: whereHelperstring{field: "\"artisan_media\".\"artisan_profile_id\""},
	MediaKind:        whereHelperstring{field: "\"artisan_media\".\"media_kind\""},
	ObjectKey:        whereHelperstring{field: "\"artisan_media\".\"object_key\""},
	OriginalFilename: whereHelpernull_String{field: "\"artisan_media\".\"original_filename\""},
	MediaType:        whereHelperstring{field: "\"artisan_media\".\"media_type\""},
	SizeBytes:        whereHelperint64{field: "\"artisan_media\".\"size_bytes\""},
	ChecksumSha256:   whereHelpernull_String{field: "\"artisan_media\".\"checksum_sha256\""},
	SortOrder:        whereHelperint{field: "\"artisan_media\".\"sort_order\""},
	Visibility:       whereHelperstring{field: "\"artisan_media\".\"visibility\""},
	CreatedAt:        whereHelpertime_Time{field: "\"artisan_media\".\"created_at\""},
}

// ArtisanMediumRels is where relationship names are stored.
var ArtisanMediumRels = struct {
	ArtisanProfile string
}{
	ArtisanProfile: "ArtisanProfile",
}

// artisanMediumR is where relationships are stored.
type artisanMediumR struct {
	ArtisanProfile *ArtisanProfile `boil:"ArtisanProfile" json:"ArtisanProfile" toml:"ArtisanProfile" yaml:"ArtisanProfile"`
}

// NewStruct creates a new relationship struct
func (*artisanMediumR) NewStruct() *artisanMediumR {
	return &artisanMediumR{}
}

func (o *ArtisanMedium) GetArtisanProfile() *ArtisanProfile {
	if o == nil {
		return nil
	}

	return o.R.GetArtisanProfile()
}

func (r *artisanMediumR) GetArtisanProfile() *ArtisanProfile {
	if r == nil {
		return nil
	}

	return r.ArtisanProfile
}

// artisanMediumL is where Load methods for each relationship are stored.
type artisanMediumL struct{}

var (
	artisanMediumAllColumns            = []string{"id", "artisan_profile_id", "media_kind", "object_key", "original_filename", "media_type", "size_bytes", "checksum_sha256", "sort_order", "visibility", "created_at"}
	artisanMediumColumnsWithoutDefault = []string{"artisan_profile_id", "media_kind", "object_key", "media_type", "size_bytes"}
	artisanMediumColumnsWithDefault    = []string{"id", "original_filename", "checksum_sha256", "sort_order", "visibility", "created_at"}
	artisanMediumPrimaryKeyColumns     = []string{"id"}
	artisanMediumGeneratedColumns      = []string{}
)

type (
	// ArtisanMediumSlice is an alias for a slice of pointers to ArtisanMedium.
	// This should almost always be used instead of []ArtisanMedium.
	ArtisanMediumSlice []*ArtisanMedium
	// ArtisanMediumHook is the signature for custom ArtisanMedium hook methods
	ArtisanMediumHook func(context.Context, boil.ContextExecutor, *ArtisanMedium) error

	artisanMediumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	artisanMediumType                 = reflect.TypeOf(&ArtisanMedium{})
	artisanMediumMapping              = queries.MakeStructMapping(artisanMediumType)
	artisanMediumPrimaryKeyMapping, _ = queries.BindMapping(artisanMediumType, artisanMediumMapping, artisanMediumPrimaryKeyColumns)
	artisanMediumInsertCacheMut       sync.RWMutex
	artisanMediumInsertCache          = make(map[string]insertCache)
	artisanMediumUpdateCacheMut       sync.RWMutex
	artisanMediumUpdateCache          = make(map[string]updateCache)
	artisanMediumUpsertCacheMut       sync.RWMutex
	artisanMediumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var artisanMediumAfterSelectMu sync.Mutex
var artisanMediumAfterSelectHooks []ArtisanMediumHook

var artisanMediumBeforeInsertMu sync.Mutex
var artisanMediumBeforeInsertHooks []ArtisanMediumHook
var artisanMediumAfterInsertMu sync.Mutex
var artisanMediumAfterInsertHooks []ArtisanMediumHook

var artisanMediumBeforeUpdateMu sync.Mutex
var artisanMediumBeforeUpdateHooks []ArtisanMediumHook
var artisanMediumAfterUpdateMu sync.Mutex
var artisanMediumAfterUpdateHooks []ArtisanMediumHook

var artisanMediumBeforeDeleteMu sync.Mutex
var artisanMediumBeforeDeleteHooks []ArtisanMediumHook
var artisanMediumAfterDeleteMu sync.Mutex
var artisanMediumAfterDeleteHooks []ArtisanMediumHook

var artisanMediumBeforeUpsertMu sync.Mutex
var artisanMediumBeforeUpsertHooks []ArtisanMediumHook
var artisanMediumAfterUpsertMu sync.Mutex
var artisanMediumAfterUpsertHooks []ArtisanMediumHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ArtisanMedium) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanMediumAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ArtisanMedium) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanMediumBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ArtisanMedium) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanMediumAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ArtisanMedium) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanMediumBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ArtisanMedium) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanMediumAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ArtisanMedium) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanMediumBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ArtisanMedium) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanMediumAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ArtisanMedium) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanMediumBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ArtisanMedium) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanMediumAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddArtisanMediumHook registers your hook function for all future operations.
func AddArtisanMediumHook(hookPoint boil.HookPoint, artisanMediumHook ArtisanMediumHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		artisanMediumAfterSelectMu.Lock()
		artisanMediumAfterSelectHooks = append(artisanMediumAfterSelectHooks, artisanMediumHook)
		artisanMediumAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		artisanMediumBeforeInsertMu.Lock()
		artisanMediumBeforeInsertHooks = append(artisanMediumBeforeInsertHooks, artisanMediumHook)
		artisanMediumBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		artisanMediumAfterInsertMu.Lock()
		artisanMediumAfterInsertHooks = append(artisanMediumAfterInsertHooks, artisanMediumHook)
		artisanMediumAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		artisanMediumBeforeUpdateMu.Lock()
		artisanMediumBeforeUpdateHooks = append(artisanMediumBeforeUpdateHooks, artisanMediumHook)
		artisanMediumBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		artisanMediumAfterUpdateMu.Lock()
		artisanMediumAfterUpdateHooks = append(artisanMediumAfterUpdateHooks, artisanMediumHook)
		artisanMediumAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		artisanMediumBeforeDeleteMu.Lock()
		artisanMediumBeforeDeleteHooks = append(artisanMediumBeforeDeleteHooks, artisanMediumHook)
		artisanMediumBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		artisanMediumAfterDeleteMu.Lock()
		artisanMediumAfterDeleteHooks = append(artisanMediumAfterDeleteHooks, artisanMediumHook)
		artisanMediumAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		artisanMediumBeforeUpsertMu.Lock()
		artisanMediumBeforeUpsertHooks = append(artisanMediumBeforeUpsertHooks, artisanMediumHook)
		artisanMediumBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		artisanMediumAfterUpsertMu.Lock()
		artisanMediumAfterUpsertHooks = append(artisanMediumAfterUpsertHooks, artisanMediumHook)
		artisanMediumAfterUpsertMu.Unlock()
	}
}

// One returns a single artisanMedium record from the query.
func (q artisanMediumQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ArtisanMedium, error) {
	o := &ArtisanMedium{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for artisan_media")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ArtisanMedium records from the query.
func (q artisanMediumQuery) All(ctx context.Context, exec boil.ContextExecutor) (ArtisanMediumSlice, error) {
	var o []*ArtisanMedium

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ArtisanMedium slice")
	}

	if len(artisanMediumAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ArtisanMedium records in the query.
func (q artisanMediumQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count artisan_media rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q artisanMediumQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if artisan_media exists")
	}

	return count > 0, nil
}

// ArtisanProfile pointed to by the foreign key.
func (o *ArtisanMedium) ArtisanProfile(mods ...qm.QueryMod) artisanProfileQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ArtisanProfileID),
	}

	queryMods = append(queryMods, mods...)

	return ArtisanProfiles(queryMods...)
}

// LoadArtisanProfile allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (artisanMediumL) LoadArtisanProfile(ctx context.Context, e boil.ContextExecutor, singular bool, maybeArtisanMedium interface{}, mods queries.Applicator) error {
	var slice []*ArtisanMedium
	var object *ArtisanMedium

	if singular {
		var ok bool
		object, ok = maybeArtisanMedium.(*ArtisanMedium)
		if !ok {
			object = new(ArtisanMedium)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeArtisanMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeArtisanMedium))
			}
		}
	} else {
		s, ok := maybeArtisanMedium.(*[]*ArtisanMedium)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeArtisanMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeArtisanMedium))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &artisanMediumR{}
		}
		args[object.ArtisanProfileID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &artisanMediumR{}
			}

			args[obj.ArtisanProfileID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`artisan_profiles`),
		qm.WhereIn(`artisan_profiles.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ArtisanProfile")
	}

	var resultSlice []*ArtisanProfile
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ArtisanProfile")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for artisan_profiles")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for artisan_profiles")
	}

	if len(artisanProfileAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ArtisanProfile = foreign
		if foreign.R == nil {
			foreign.R = &artisanProfileR{}
		}
		foreign.R.ArtisanMedia = append(foreign.R.ArtisanMedia, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ArtisanProfileID == foreign.ID {
				local.R.ArtisanProfile = foreign
				if foreign.R == nil {
					foreign.R = &artisanProfileR{}
				}
				foreign.R.ArtisanMedia = append(foreign.R.ArtisanMedia, local)
				break
			}
		}
	}

	return nil
}

// SetArtisanProfile of the artisanMedium to the related item.
// Sets o.R.ArtisanProfile to related.
// Adds o to related.R.ArtisanMedia.
func (o *ArtisanMedium) SetArtisanProfile(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ArtisanProfile) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"artisan_media\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"artisan_profile_id"}),
		strmangle.WhereClause("\"", "\"", 2, artisanMediumPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ArtisanProfileID = related.ID
	if o.R == nil {
		o.R = &artisanMediumR{
			ArtisanProfile: related,
		}
	} else {
		o.R.ArtisanProfile = related
	}

	if related.R == nil {
		related.R = &artisanProfileR{
			ArtisanMedia: ArtisanMediumSlice{o},
		}
	} else {
		related.R.ArtisanMedia = append(related.R.ArtisanMedia, o)
	}

	return nil
}

// ArtisanMedia retrieves all the records using an executor.
func ArtisanMedia(mods ...qm.QueryMod) artisanMediumQuery {
	mods = append(mods, qm.From("\"artisan_media\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"artisan_media\".*"})
	}

	return artisanMediumQuery{q}
}

// FindArtisanMedium retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindArtisanMedium(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*ArtisanMedium, error) {
	artisanMediumObj := &ArtisanMedium{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"artisan_media\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, artisanMediumObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from artisan_media")
	}

	if err = artisanMediumObj.doAfterSelectHooks(ctx, exec); err != nil {
		return artisanMediumObj, err
	}

	return artisanMediumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ArtisanMedium) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no artisan_media provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(artisanMediumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	artisanMediumInsertCacheMut.RLock()
	cache, cached := artisanMediumInsertCache[key]
	artisanMediumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			artisanMediumAllColumns,
			artisanMediumColumnsWithDefault,
			artisanMediumColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(artisanMediumType, artisanMediumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(artisanMediumType, artisanMediumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"artisan_media\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"artisan_media\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into artisan_media")
	}

	if !cached {
		artisanMediumInsertCacheMut.Lock()
		artisanMediumInsertCache[key] = cache
		artisanMediumInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ArtisanMedium.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ArtisanMedium) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	artisanMediumUpdateCacheMut.RLock()
	cache, cached := artisanMediumUpdateCache[key]
	artisanMediumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			artisanMediumAllColumns,
			artisanMediumPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update artisan_media, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"artisan_media\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, artisanMediumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(artisanMediumType, artisanMediumMapping, append(wl, artisanMediumPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update artisan_media row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for artisan_media")
	}

	if !cached {
		artisanMediumUpdateCacheMut.Lock()
		artisanMediumUpdateCache[key] = cache
		artisanMediumUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q artisanMediumQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for artisan_media")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for artisan_media")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ArtisanMediumSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), artisanMediumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"artisan_media\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, artisanMediumPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in artisanMedium slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all artisanMedium")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ArtisanMedium) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no artisan_media provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(artisanMediumColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	artisanMediumUpsertCacheMut.RLock()
	cache, cached := artisanMediumUpsertCache[key]
	artisanMediumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			artisanMediumAllColumns,
			artisanMediumColumnsWithDefault,
			artisanMediumColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			artisanMediumAllColumns,
			artisanMediumPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert artisan_media, could not build update column list")
		}

		ret := strmangle.SetComplement(artisanMediumAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(artisanMediumPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert artisan_media, could not build conflict column list")
			}

			conflict = make([]string, len(artisanMediumPrimaryKeyColumns))
			copy(conflict, artisanMediumPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"artisan_media\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(artisanMediumType, artisanMediumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(artisanMediumType, artisanMediumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert artisan_media")
	}

	if !cached {
		artisanMediumUpsertCacheMut.Lock()
		artisanMediumUpsertCache[key] = cache
		artisanMediumUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ArtisanMedium record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ArtisanMedium) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ArtisanMedium provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), artisanMediumPrimaryKeyMapping)
	sql := "DELETE FROM \"artisan_media\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from artisan_media")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for artisan_media")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q artisanMediumQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no artisanMediumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from artisan_media")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for artisan_media")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ArtisanMediumSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(artisanMediumBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), artisanMediumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"artisan_media\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, artisanMediumPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from artisanMedium slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for artisan_media")
	}

	if len(artisanMediumAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ArtisanMedium) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindArtisanMedium(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ArtisanMediumSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ArtisanMediumSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), artisanMediumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"artisan_media\".* FROM \"artisan_media\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, artisanMediumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ArtisanMediumSlice")
	}

	*o = slice

	return nil
}

// ArtisanMediumExists checks if the ArtisanMedium row exists.
func ArtisanMediumExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"artisan_media\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if artisan_media exists")
	}

	return exists, nil
}

// Exists checks if the ArtisanMedium row exists.
func (o *ArtisanMedium) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ArtisanMediumExists(ctx, exec, o.ID)
}
