// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Addresses                  string
	ArtisanDocuments           string
	ArtisanMedia               string
	ArtisanProfileCategories   string
	ArtisanProfileTranslations string
	ArtisanProfiles            string
	AuditEvents                string
	Categories                 string
	IdempotencyKeys            string
	OutboxEvents               string
	ProductMedia               string
	ProductTranslations        string
	Products                   string
	Roles                      string
	Sessions                   string
	UserRoles                  string
	Users                      string
}{
	Addresses:                  "addresses",
	ArtisanDocuments:           "artisan_documents",
	ArtisanMedia:               "artisan_media",
	ArtisanProfileCategories:   "artisan_profile_categories",
	ArtisanProfileTranslations: "artisan_profile_translations",
	ArtisanProfiles:            "artisan_profiles",
	AuditEvents:                "audit_events",
	Categories:                 "categories",
	IdempotencyKeys:            "idempotency_keys",
	OutboxEvents:               "outbox_events",
	ProductMedia:               "product_media",
	ProductTranslations:        "product_translations",
	Products:                   "products",
	Roles:                      "roles",
	Sessions:                   "sessions",
	UserRoles:                  "user_roles",
	Users:                      "users",
}
