// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire

package container

import (
	"context"

	"github.com/aisha-platform/aisha/apps/api/internal/config"
)

// Initialize is the checked-in generated injector used by normal builds.
func Initialize(ctx context.Context, cfg config.Config) (*Runtime, error) {
	return NewRuntime(ctx, cfg)
}
