//go:build wireinject

package container

import (
	"context"

	"github.com/aisha-platform/aisha/apps/api/internal/config"
	"github.com/google/wire"
)

// Initialize is generated by Wire for the wireinject build.
func Initialize(context.Context, config.Config) (*Runtime, error) {
	wire.Build(ProviderSet)
	return nil, nil
}
