// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ArtisanProfileCategory is an object representing the database table.
type ArtisanProfileCategory struct {
	ArtisanProfileID string    `boil:"artisan_profile_id" json:"artisan_profile_id" toml:"artisan_profile_id" yaml:"artisan_profile_id"`
	CategoryID       string    `boil:"category_id" json:"category_id" toml:"category_id" yaml:"category_id"`
	CreatedAt        time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *artisanProfileCategoryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L artisanProfileCategoryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ArtisanProfileCategoryColumns = struct {
	ArtisanProfileID string
	CategoryID       string
	CreatedAt        string
}{
	ArtisanProfileID: "artisan_profile_id",
	CategoryID:       "category_id",
	CreatedAt:        "created_at",
}

var ArtisanProfileCategoryTableColumns = struct {
	ArtisanProfileID string
	CategoryID       string
	CreatedAt        string
}{
	ArtisanProfileID: "artisan_profile_categories.artisan_profile_id",
	CategoryID:       "artisan_profile_categories.category_id",
	CreatedAt:        "artisan_profile_categories.created_at",
}

// Generated where

var ArtisanProfileCategoryWhere = struct {
	ArtisanProfileID whereHelperstring
	CategoryID       whereHelperstring
	CreatedAt        whereHelpertime_Time
}{
	ArtisanProfileID: whereHelperstring{field: "\"artisan_profile_categories\".\"artisan_profile_id\""},
	CategoryID:       whereHelperstring{field: "\"artisan_profile_categories\".\"category_id\""},
	CreatedAt:        whereHelpertime_Time{field: "\"artisan_profile_categories\".\"created_at\""},
}

// ArtisanProfileCategoryRels is where relationship names are stored.
var ArtisanProfileCategoryRels = struct {
	Category       string
	ArtisanProfile string
}{
	Category:       "Category",
	ArtisanProfile: "ArtisanProfile",
}

// artisanProfileCategoryR is where relationships are stored.
type artisanProfileCategoryR struct {
	Category       *Category       `boil:"Category" json:"Category" toml:"Category" yaml:"Category"`
	ArtisanProfile *ArtisanProfile `boil:"ArtisanProfile" json:"ArtisanProfile" toml:"ArtisanProfile" yaml:"ArtisanProfile"`
}

// NewStruct creates a new relationship struct
func (*artisanProfileCategoryR) NewStruct() *artisanProfileCategoryR {
	return &artisanProfileCategoryR{}
}

func (o *ArtisanProfileCategory) GetCategory() *Category {
	if o == nil {
		return nil
	}

	return o.R.GetCategory()
}

func (r *artisanProfileCategoryR) GetCategory() *Category {
	if r == nil {
		return nil
	}

	return r.Category
}

func (o *ArtisanProfileCategory) GetArtisanProfile() *ArtisanProfile {
	if o == nil {
		return nil
	}

	return o.R.GetArtisanProfile()
}

func (r *artisanProfileCategoryR) GetArtisanProfile() *ArtisanProfile {
	if r == nil {
		return nil
	}

	return r.ArtisanProfile
}

// artisanProfileCategoryL is where Load methods for each relationship are stored.
type artisanProfileCategoryL struct{}

var (
	artisanProfileCategoryAllColumns            = []string{"artisan_profile_id", "category_id", "created_at"}
	artisanProfileCategoryColumnsWithoutDefault = []string{"artisan_profile_id", "category_id"}
	artisanProfileCategoryColumnsWithDefault    = []string{"created_at"}
	artisanProfileCategoryPrimaryKeyColumns     = []string{"artisan_profile_id", "category_id"}
	artisanProfileCategoryGeneratedColumns      = []string{}
)

type (
	// ArtisanProfileCategorySlice is an alias for a slice of pointers to ArtisanProfileCategory.
	// This should almost always be used instead of []ArtisanProfileCategory.
	ArtisanProfileCategorySlice []*ArtisanProfileCategory
	// ArtisanProfileCategoryHook is the signature for custom ArtisanProfileCategory hook methods
	ArtisanProfileCategoryHook func(context.Context, boil.ContextExecutor, *ArtisanProfileCategory) error

	artisanProfileCategoryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	artisanProfileCategoryType                 = reflect.TypeOf(&ArtisanProfileCategory{})
	artisanProfileCategoryMapping              = queries.MakeStructMapping(artisanProfileCategoryType)
	artisanProfileCategoryPrimaryKeyMapping, _ = queries.BindMapping(artisanProfileCategoryType, artisanProfileCategoryMapping, artisanProfileCategoryPrimaryKeyColumns)
	artisanProfileCategoryInsertCacheMut       sync.RWMutex
	artisanProfileCategoryInsertCache          = make(map[string]insertCache)
	artisanProfileCategoryUpdateCacheMut       sync.RWMutex
	artisanProfileCategoryUpdateCache          = make(map[string]updateCache)
	artisanProfileCategoryUpsertCacheMut       sync.RWMutex
	artisanProfileCategoryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var artisanProfileCategoryAfterSelectMu sync.Mutex
var artisanProfileCategoryAfterSelectHooks []ArtisanProfileCategoryHook

var artisanProfileCategoryBeforeInsertMu sync.Mutex
var artisanProfileCategoryBeforeInsertHooks []ArtisanProfileCategoryHook
var artisanProfileCategoryAfterInsertMu sync.Mutex
var artisanProfileCategoryAfterInsertHooks []ArtisanProfileCategoryHook

var artisanProfileCategoryBeforeUpdateMu sync.Mutex
var artisanProfileCategoryBeforeUpdateHooks []ArtisanProfileCategoryHook
var artisanProfileCategoryAfterUpdateMu sync.Mutex
var artisanProfileCategoryAfterUpdateHooks []ArtisanProfileCategoryHook

var artisanProfileCategoryBeforeDeleteMu sync.Mutex
var artisanProfileCategoryBeforeDeleteHooks []ArtisanProfileCategoryHook
var artisanProfileCategoryAfterDeleteMu sync.Mutex
var artisanProfileCategoryAfterDeleteHooks []ArtisanProfileCategoryHook

var artisanProfileCategoryBeforeUpsertMu sync.Mutex
var artisanProfileCategoryBeforeUpsertHooks []ArtisanProfileCategoryHook
var artisanProfileCategoryAfterUpsertMu sync.Mutex
var artisanProfileCategoryAfterUpsertHooks []ArtisanProfileCategoryHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ArtisanProfileCategory) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileCategoryAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ArtisanProfileCategory) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileCategoryBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ArtisanProfileCategory) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileCategoryAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ArtisanProfileCategory) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileCategoryBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ArtisanProfileCategory) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileCategoryAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ArtisanProfileCategory) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileCategoryBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ArtisanProfileCategory) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileCategoryAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ArtisanProfileCategory) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileCategoryBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ArtisanProfileCategory) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileCategoryAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddArtisanProfileCategoryHook registers your hook function for all future operations.
func AddArtisanProfileCategoryHook(hookPoint boil.HookPoint, artisanProfileCategoryHook ArtisanProfileCategoryHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		artisanProfileCategoryAfterSelectMu.Lock()
		artisanProfileCategoryAfterSelectHooks = append(artisanProfileCategoryAfterSelectHooks, artisanProfileCategoryHook)
		artisanProfileCategoryAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		artisanProfileCategoryBeforeInsertMu.Lock()
		artisanProfileCategoryBeforeInsertHooks = append(artisanProfileCategoryBeforeInsertHooks, artisanProfileCategoryHook)
		artisanProfileCategoryBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		artisanProfileCategoryAfterInsertMu.Lock()
		artisanProfileCategoryAfterInsertHooks = append(artisanProfileCategoryAfterInsertHooks, artisanProfileCategoryHook)
		artisanProfileCategoryAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		artisanProfileCategoryBeforeUpdateMu.Lock()
		artisanProfileCategoryBeforeUpdateHooks = append(artisanProfileCategoryBeforeUpdateHooks, artisanProfileCategoryHook)
		artisanProfileCategoryBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		artisanProfileCategoryAfterUpdateMu.Lock()
		artisanProfileCategoryAfterUpdateHooks = append(artisanProfileCategoryAfterUpdateHooks, artisanProfileCategoryHook)
		artisanProfileCategoryAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		artisanProfileCategoryBeforeDeleteMu.Lock()
		artisanProfileCategoryBeforeDeleteHooks = append(artisanProfileCategoryBeforeDeleteHooks, artisanProfileCategoryHook)
		artisanProfileCategoryBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		artisanProfileCategoryAfterDeleteMu.Lock()
		artisanProfileCategoryAfterDeleteHooks = append(artisanProfileCategoryAfterDeleteHooks, artisanProfileCategoryHook)
		artisanProfileCategoryAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		artisanProfileCategoryBeforeUpsertMu.Lock()
		artisanProfileCategoryBeforeUpsertHooks = append(artisanProfileCategoryBeforeUpsertHooks, artisanProfileCategoryHook)
		artisanProfileCategoryBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		artisanProfileCategoryAfterUpsertMu.Lock()
		artisanProfileCategoryAfterUpsertHooks = append(artisanProfileCategoryAfterUpsertHooks, artisanProfileCategoryHook)
		artisanProfileCategoryAfterUpsertMu.Unlock()
	}
}

// One returns a single artisanProfileCategory record from the query.
func (q artisanProfileCategoryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ArtisanProfileCategory, error) {
	o := &ArtisanProfileCategory{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for artisan_profile_categories")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ArtisanProfileCategory records from the query.
func (q artisanProfileCategoryQuery) All(ctx context.Context, exec boil.ContextExecutor) (ArtisanProfileCategorySlice, error) {
	var o []*ArtisanProfileCategory

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ArtisanProfileCategory slice")
	}

	if len(artisanProfileCategoryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ArtisanProfileCategory records in the query.
func (q artisanProfileCategoryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count artisan_profile_categories rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q artisanProfileCategoryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if artisan_profile_categories exists")
	}

	return count > 0, nil
}

// Category pointed to by the foreign key.
func (o *ArtisanProfileCategory) Category(mods ...qm.QueryMod) categoryQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CategoryID),
	}

	queryMods = append(queryMods, mods...)

	return Categories(queryMods...)
}

// ArtisanProfile pointed to by the foreign key.
func (o *ArtisanProfileCategory) ArtisanProfile(mods ...qm.QueryMod) artisanProfileQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ArtisanProfileID),
	}

	queryMods = append(queryMods, mods...)

	return ArtisanProfiles(queryMods...)
}

// LoadCategory allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (artisanProfileCategoryL) LoadCategory(ctx context.Context, e boil.ContextExecutor, singular bool, maybeArtisanProfileCategory interface{}, mods queries.Applicator) error {
	var slice []*ArtisanProfileCategory
	var object *ArtisanProfileCategory

	if singular {
		var ok bool
		object, ok = maybeArtisanProfileCategory.(*ArtisanProfileCategory)
		if !ok {
			object = new(ArtisanProfileCategory)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeArtisanProfileCategory)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeArtisanProfileCategory))
			}
		}
	} else {
		s, ok := maybeArtisanProfileCategory.(*[]*ArtisanProfileCategory)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeArtisanProfileCategory)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeArtisanProfileCategory))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &artisanProfileCategoryR{}
		}
		args[object.CategoryID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &artisanProfileCategoryR{}
			}

			args[obj.CategoryID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`categories`),
		qm.WhereIn(`categories.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Category")
	}

	var resultSlice []*Category
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Category")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for categories")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for categories")
	}

	if len(categoryAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Category = foreign
		if foreign.R == nil {
			foreign.R = &categoryR{}
		}
		foreign.R.ArtisanProfileCategories = append(foreign.R.ArtisanProfileCategories, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CategoryID == foreign.ID {
				local.R.Category = foreign
				if foreign.R == nil {
					foreign.R = &categoryR{}
				}
				foreign.R.ArtisanProfileCategories = append(foreign.R.ArtisanProfileCategories, local)
				break
			}
		}
	}

	return nil
}

// LoadArtisanProfile allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (artisanProfileCategoryL) LoadArtisanProfile(ctx context.Context, e boil.ContextExecutor, singular bool, maybeArtisanProfileCategory interface{}, mods queries.Applicator) error {
	var slice []*ArtisanProfileCategory
	var object *ArtisanProfileCategory

	if singular {
		var ok bool
		object, ok = maybeArtisanProfileCategory.(*ArtisanProfileCategory)
		if !ok {
			object = new(ArtisanProfileCategory)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeArtisanProfileCategory)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeArtisanProfileCategory))
			}
		}
	} else {
		s, ok := maybeArtisanProfileCategory.(*[]*ArtisanProfileCategory)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeArtisanProfileCategory)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeArtisanProfileCategory))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &artisanProfileCategoryR{}
		}
		args[object.ArtisanProfileID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &artisanProfileCategoryR{}
			}

			args[obj.ArtisanProfileID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`artisan_profiles`),
		qm.WhereIn(`artisan_profiles.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ArtisanProfile")
	}

	var resultSlice []*ArtisanProfile
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ArtisanProfile")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for artisan_profiles")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for artisan_profiles")
	}

	if len(artisanProfileAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ArtisanProfile = foreign
		if foreign.R == nil {
			foreign.R = &artisanProfileR{}
		}
		foreign.R.ArtisanProfileCategories = append(foreign.R.ArtisanProfileCategories, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ArtisanProfileID == foreign.ID {
				local.R.ArtisanProfile = foreign
				if foreign.R == nil {
					foreign.R = &artisanProfileR{}
				}
				foreign.R.ArtisanProfileCategories = append(foreign.R.ArtisanProfileCategories, local)
				break
			}
		}
	}

	return nil
}

// SetCategory of the artisanProfileCategory to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.ArtisanProfileCategories.
func (o *ArtisanProfileCategory) SetCategory(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Category) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"artisan_profile_categories\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"category_id"}),
		strmangle.WhereClause("\"", "\"", 2, artisanProfileCategoryPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ArtisanProfileID, o.CategoryID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CategoryID = related.ID
	if o.R == nil {
		o.R = &artisanProfileCategoryR{
			Category: related,
		}
	} else {
		o.R.Category = related
	}

	if related.R == nil {
		related.R = &categoryR{
			ArtisanProfileCategories: ArtisanProfileCategorySlice{o},
		}
	} else {
		related.R.ArtisanProfileCategories = append(related.R.ArtisanProfileCategories, o)
	}

	return nil
}

// SetArtisanProfile of the artisanProfileCategory to the related item.
// Sets o.R.ArtisanProfile to related.
// Adds o to related.R.ArtisanProfileCategories.
func (o *ArtisanProfileCategory) SetArtisanProfile(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ArtisanProfile) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"artisan_profile_categories\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"artisan_profile_id"}),
		strmangle.WhereClause("\"", "\"", 2, artisanProfileCategoryPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ArtisanProfileID, o.CategoryID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ArtisanProfileID = related.ID
	if o.R == nil {
		o.R = &artisanProfileCategoryR{
			ArtisanProfile: related,
		}
	} else {
		o.R.ArtisanProfile = related
	}

	if related.R == nil {
		related.R = &artisanProfileR{
			ArtisanProfileCategories: ArtisanProfileCategorySlice{o},
		}
	} else {
		related.R.ArtisanProfileCategories = append(related.R.ArtisanProfileCategories, o)
	}

	return nil
}

// ArtisanProfileCategories retrieves all the records using an executor.
func ArtisanProfileCategories(mods ...qm.QueryMod) artisanProfileCategoryQuery {
	mods = append(mods, qm.From("\"artisan_profile_categories\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"artisan_profile_categories\".*"})
	}

	return artisanProfileCategoryQuery{q}
}

// FindArtisanProfileCategory retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindArtisanProfileCategory(ctx context.Context, exec boil.ContextExecutor, artisanProfileID string, categoryID string, selectCols ...string) (*ArtisanProfileCategory, error) {
	artisanProfileCategoryObj := &ArtisanProfileCategory{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"artisan_profile_categories\" where \"artisan_profile_id\"=$1 AND \"category_id\"=$2", sel,
	)

	q := queries.Raw(query, artisanProfileID, categoryID)

	err := q.Bind(ctx, exec, artisanProfileCategoryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from artisan_profile_categories")
	}

	if err = artisanProfileCategoryObj.doAfterSelectHooks(ctx, exec); err != nil {
		return artisanProfileCategoryObj, err
	}

	return artisanProfileCategoryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ArtisanProfileCategory) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no artisan_profile_categories provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(artisanProfileCategoryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	artisanProfileCategoryInsertCacheMut.RLock()
	cache, cached := artisanProfileCategoryInsertCache[key]
	artisanProfileCategoryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			artisanProfileCategoryAllColumns,
			artisanProfileCategoryColumnsWithDefault,
			artisanProfileCategoryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(artisanProfileCategoryType, artisanProfileCategoryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(artisanProfileCategoryType, artisanProfileCategoryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"artisan_profile_categories\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"artisan_profile_categories\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into artisan_profile_categories")
	}

	if !cached {
		artisanProfileCategoryInsertCacheMut.Lock()
		artisanProfileCategoryInsertCache[key] = cache
		artisanProfileCategoryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ArtisanProfileCategory.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ArtisanProfileCategory) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	artisanProfileCategoryUpdateCacheMut.RLock()
	cache, cached := artisanProfileCategoryUpdateCache[key]
	artisanProfileCategoryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			artisanProfileCategoryAllColumns,
			artisanProfileCategoryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update artisan_profile_categories, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"artisan_profile_categories\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, artisanProfileCategoryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(artisanProfileCategoryType, artisanProfileCategoryMapping, append(wl, artisanProfileCategoryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update artisan_profile_categories row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for artisan_profile_categories")
	}

	if !cached {
		artisanProfileCategoryUpdateCacheMut.Lock()
		artisanProfileCategoryUpdateCache[key] = cache
		artisanProfileCategoryUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q artisanProfileCategoryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for artisan_profile_categories")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for artisan_profile_categories")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ArtisanProfileCategorySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), artisanProfileCategoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"artisan_profile_categories\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, artisanProfileCategoryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in artisanProfileCategory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all artisanProfileCategory")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ArtisanProfileCategory) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no artisan_profile_categories provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(artisanProfileCategoryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	artisanProfileCategoryUpsertCacheMut.RLock()
	cache, cached := artisanProfileCategoryUpsertCache[key]
	artisanProfileCategoryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			artisanProfileCategoryAllColumns,
			artisanProfileCategoryColumnsWithDefault,
			artisanProfileCategoryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			artisanProfileCategoryAllColumns,
			artisanProfileCategoryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert artisan_profile_categories, could not build update column list")
		}

		ret := strmangle.SetComplement(artisanProfileCategoryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(artisanProfileCategoryPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert artisan_profile_categories, could not build conflict column list")
			}

			conflict = make([]string, len(artisanProfileCategoryPrimaryKeyColumns))
			copy(conflict, artisanProfileCategoryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"artisan_profile_categories\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(artisanProfileCategoryType, artisanProfileCategoryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(artisanProfileCategoryType, artisanProfileCategoryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert artisan_profile_categories")
	}

	if !cached {
		artisanProfileCategoryUpsertCacheMut.Lock()
		artisanProfileCategoryUpsertCache[key] = cache
		artisanProfileCategoryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ArtisanProfileCategory record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ArtisanProfileCategory) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ArtisanProfileCategory provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), artisanProfileCategoryPrimaryKeyMapping)
	sql := "DELETE FROM \"artisan_profile_categories\" WHERE \"artisan_profile_id\"=$1 AND \"category_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from artisan_profile_categories")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for artisan_profile_categories")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q artisanProfileCategoryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no artisanProfileCategoryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from artisan_profile_categories")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for artisan_profile_categories")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ArtisanProfileCategorySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(artisanProfileCategoryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), artisanProfileCategoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"artisan_profile_categories\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, artisanProfileCategoryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from artisanProfileCategory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for artisan_profile_categories")
	}

	if len(artisanProfileCategoryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ArtisanProfileCategory) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindArtisanProfileCategory(ctx, exec, o.ArtisanProfileID, o.CategoryID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ArtisanProfileCategorySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ArtisanProfileCategorySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), artisanProfileCategoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"artisan_profile_categories\".* FROM \"artisan_profile_categories\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, artisanProfileCategoryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ArtisanProfileCategorySlice")
	}

	*o = slice

	return nil
}

// ArtisanProfileCategoryExists checks if the ArtisanProfileCategory row exists.
func ArtisanProfileCategoryExists(ctx context.Context, exec boil.ContextExecutor, artisanProfileID string, categoryID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"artisan_profile_categories\" where \"artisan_profile_id\"=$1 AND \"category_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, artisanProfileID, categoryID)
	}
	row := exec.QueryRowContext(ctx, sql, artisanProfileID, categoryID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if artisan_profile_categories exists")
	}

	return exists, nil
}

// Exists checks if the ArtisanProfileCategory row exists.
func (o *ArtisanProfileCategory) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ArtisanProfileCategoryExists(ctx, exec, o.ArtisanProfileID, o.CategoryID)
}
