// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ArtisanProfileTranslation is an object representing the database table.
type ArtisanProfileTranslation struct {
	ArtisanProfileID string      `boil:"artisan_profile_id" json:"artisan_profile_id" toml:"artisan_profile_id" yaml:"artisan_profile_id"`
	Locale           string      `boil:"locale" json:"locale" toml:"locale" yaml:"locale"`
	Biography        null.String `boil:"biography" json:"biography,omitempty" toml:"biography" yaml:"biography,omitempty"`
	CreatedAt        time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt        time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *artisanProfileTranslationR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L artisanProfileTranslationL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ArtisanProfileTranslationColumns = struct {
	ArtisanProfileID string
	Locale           string
	Biography        string
	CreatedAt        string
	UpdatedAt        string
}{
	ArtisanProfileID: "artisan_profile_id",
	Locale:           "locale",
	Biography:        "biography",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}

var ArtisanProfileTranslationTableColumns = struct {
	ArtisanProfileID string
	Locale           string
	Biography        string
	CreatedAt        string
	UpdatedAt        string
}{
	ArtisanProfileID: "artisan_profile_translations.artisan_profile_id",
	Locale:           "artisan_profile_translations.locale",
	Biography:        "artisan_profile_translations.biography",
	CreatedAt:        "artisan_profile_translations.created_at",
	UpdatedAt:        "artisan_profile_translations.updated_at",
}

// Generated where

var ArtisanProfileTranslationWhere = struct {
	ArtisanProfileID whereHelperstring
	Locale           whereHelperstring
	Biography        whereHelpernull_String
	CreatedAt        whereHelpertime_Time
	UpdatedAt        whereHelpertime_Time
}{
	ArtisanProfileID: whereHelperstring{field: "\"artisan_profile_translations\".\"artisan_profile_id\""},
	Locale:           whereHelperstring{field: "\"artisan_profile_translations\".\"locale\""},
	Biography:        whereHelpernull_String{field: "\"artisan_profile_translations\".\"biography\""},
	CreatedAt:        whereHelpertime_Time{field: "\"artisan_profile_translations\".\"created_at\""},
	UpdatedAt:        whereHelpertime_Time{field: "\"artisan_profile_translations\".\"updated_at\""},
}

// ArtisanProfileTranslationRels is where relationship names are stored.
var ArtisanProfileTranslationRels = struct {
	ArtisanProfile string
}{
	ArtisanProfile: "ArtisanProfile",
}

// artisanProfileTranslationR is where relationships are stored.
type artisanProfileTranslationR struct {
	ArtisanProfile *ArtisanProfile `boil:"ArtisanProfile" json:"ArtisanProfile" toml:"ArtisanProfile" yaml:"ArtisanProfile"`
}

// NewStruct creates a new relationship struct
func (*artisanProfileTranslationR) NewStruct() *artisanProfileTranslationR {
	return &artisanProfileTranslationR{}
}

func (o *ArtisanProfileTranslation) GetArtisanProfile() *ArtisanProfile {
	if o == nil {
		return nil
	}

	return o.R.GetArtisanProfile()
}

func (r *artisanProfileTranslationR) GetArtisanProfile() *ArtisanProfile {
	if r == nil {
		return nil
	}

	return r.ArtisanProfile
}

// artisanProfileTranslationL is where Load methods for each relationship are stored.
type artisanProfileTranslationL struct{}

var (
	artisanProfileTranslationAllColumns            = []string{"artisan_profile_id", "locale", "biography", "created_at", "updated_at"}
	artisanProfileTranslationColumnsWithoutDefault = []string{"artisan_profile_id", "locale"}
	artisanProfileTranslationColumnsWithDefault    = []string{"biography", "created_at", "updated_at"}
	artisanProfileTranslationPrimaryKeyColumns     = []string{"artisan_profile_id", "locale"}
	artisanProfileTranslationGeneratedColumns      = []string{}
)

type (
	// ArtisanProfileTranslationSlice is an alias for a slice of pointers to ArtisanProfileTranslation.
	// This should almost always be used instead of []ArtisanProfileTranslation.
	ArtisanProfileTranslationSlice []*ArtisanProfileTranslation
	// ArtisanProfileTranslationHook is the signature for custom ArtisanProfileTranslation hook methods
	ArtisanProfileTranslationHook func(context.Context, boil.ContextExecutor, *ArtisanProfileTranslation) error

	artisanProfileTranslationQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	artisanProfileTranslationType                 = reflect.TypeOf(&ArtisanProfileTranslation{})
	artisanProfileTranslationMapping              = queries.MakeStructMapping(artisanProfileTranslationType)
	artisanProfileTranslationPrimaryKeyMapping, _ = queries.BindMapping(artisanProfileTranslationType, artisanProfileTranslationMapping, artisanProfileTranslationPrimaryKeyColumns)
	artisanProfileTranslationInsertCacheMut       sync.RWMutex
	artisanProfileTranslationInsertCache          = make(map[string]insertCache)
	artisanProfileTranslationUpdateCacheMut       sync.RWMutex
	artisanProfileTranslationUpdateCache          = make(map[string]updateCache)
	artisanProfileTranslationUpsertCacheMut       sync.RWMutex
	artisanProfileTranslationUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var artisanProfileTranslationAfterSelectMu sync.Mutex
var artisanProfileTranslationAfterSelectHooks []ArtisanProfileTranslationHook

var artisanProfileTranslationBeforeInsertMu sync.Mutex
var artisanProfileTranslationBeforeInsertHooks []ArtisanProfileTranslationHook
var artisanProfileTranslationAfterInsertMu sync.Mutex
var artisanProfileTranslationAfterInsertHooks []ArtisanProfileTranslationHook

var artisanProfileTranslationBeforeUpdateMu sync.Mutex
var artisanProfileTranslationBeforeUpdateHooks []ArtisanProfileTranslationHook
var artisanProfileTranslationAfterUpdateMu sync.Mutex
var artisanProfileTranslationAfterUpdateHooks []ArtisanProfileTranslationHook

var artisanProfileTranslationBeforeDeleteMu sync.Mutex
var artisanProfileTranslationBeforeDeleteHooks []ArtisanProfileTranslationHook
var artisanProfileTranslationAfterDeleteMu sync.Mutex
var artisanProfileTranslationAfterDeleteHooks []ArtisanProfileTranslationHook

var artisanProfileTranslationBeforeUpsertMu sync.Mutex
var artisanProfileTranslationBeforeUpsertHooks []ArtisanProfileTranslationHook
var artisanProfileTranslationAfterUpsertMu sync.Mutex
var artisanProfileTranslationAfterUpsertHooks []ArtisanProfileTranslationHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ArtisanProfileTranslation) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileTranslationAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ArtisanProfileTranslation) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileTranslationBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ArtisanProfileTranslation) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileTranslationAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ArtisanProfileTranslation) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileTranslationBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ArtisanProfileTranslation) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileTranslationAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ArtisanProfileTranslation) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileTranslationBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ArtisanProfileTranslation) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileTranslationAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ArtisanProfileTranslation) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileTranslationBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ArtisanProfileTranslation) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range artisanProfileTranslationAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddArtisanProfileTranslationHook registers your hook function for all future operations.
func AddArtisanProfileTranslationHook(hookPoint boil.HookPoint, artisanProfileTranslationHook ArtisanProfileTranslationHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		artisanProfileTranslationAfterSelectMu.Lock()
		artisanProfileTranslationAfterSelectHooks = append(artisanProfileTranslationAfterSelectHooks, artisanProfileTranslationHook)
		artisanProfileTranslationAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		artisanProfileTranslationBeforeInsertMu.Lock()
		artisanProfileTranslationBeforeInsertHooks = append(artisanProfileTranslationBeforeInsertHooks, artisanProfileTranslationHook)
		artisanProfileTranslationBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		artisanProfileTranslationAfterInsertMu.Lock()
		artisanProfileTranslationAfterInsertHooks = append(artisanProfileTranslationAfterInsertHooks, artisanProfileTranslationHook)
		artisanProfileTranslationAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		artisanProfileTranslationBeforeUpdateMu.Lock()
		artisanProfileTranslationBeforeUpdateHooks = append(artisanProfileTranslationBeforeUpdateHooks, artisanProfileTranslationHook)
		artisanProfileTranslationBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		artisanProfileTranslationAfterUpdateMu.Lock()
		artisanProfileTranslationAfterUpdateHooks = append(artisanProfileTranslationAfterUpdateHooks, artisanProfileTranslationHook)
		artisanProfileTranslationAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		artisanProfileTranslationBeforeDeleteMu.Lock()
		artisanProfileTranslationBeforeDeleteHooks = append(artisanProfileTranslationBeforeDeleteHooks, artisanProfileTranslationHook)
		artisanProfileTranslationBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		artisanProfileTranslationAfterDeleteMu.Lock()
		artisanProfileTranslationAfterDeleteHooks = append(artisanProfileTranslationAfterDeleteHooks, artisanProfileTranslationHook)
		artisanProfileTranslationAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		artisanProfileTranslationBeforeUpsertMu.Lock()
		artisanProfileTranslationBeforeUpsertHooks = append(artisanProfileTranslationBeforeUpsertHooks, artisanProfileTranslationHook)
		artisanProfileTranslationBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		artisanProfileTranslationAfterUpsertMu.Lock()
		artisanProfileTranslationAfterUpsertHooks = append(artisanProfileTranslationAfterUpsertHooks, artisanProfileTranslationHook)
		artisanProfileTranslationAfterUpsertMu.Unlock()
	}
}

// One returns a single artisanProfileTranslation record from the query.
func (q artisanProfileTranslationQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ArtisanProfileTranslation, error) {
	o := &ArtisanProfileTranslation{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for artisan_profile_translations")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ArtisanProfileTranslation records from the query.
func (q artisanProfileTranslationQuery) All(ctx context.Context, exec boil.ContextExecutor) (ArtisanProfileTranslationSlice, error) {
	var o []*ArtisanProfileTranslation

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ArtisanProfileTranslation slice")
	}

	if len(artisanProfileTranslationAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ArtisanProfileTranslation records in the query.
func (q artisanProfileTranslationQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count artisan_profile_translations rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q artisanProfileTranslationQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if artisan_profile_translations exists")
	}

	return count > 0, nil
}

// ArtisanProfile pointed to by the foreign key.
func (o *ArtisanProfileTranslation) ArtisanProfile(mods ...qm.QueryMod) artisanProfileQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ArtisanProfileID),
	}

	queryMods = append(queryMods, mods...)

	return ArtisanProfiles(queryMods...)
}

// LoadArtisanProfile allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (artisanProfileTranslationL) LoadArtisanProfile(ctx context.Context, e boil.ContextExecutor, singular bool, maybeArtisanProfileTranslation interface{}, mods queries.Applicator) error {
	var slice []*ArtisanProfileTranslation
	var object *ArtisanProfileTranslation

	if singular {
		var ok bool
		object, ok = maybeArtisanProfileTranslation.(*ArtisanProfileTranslation)
		if !ok {
			object = new(ArtisanProfileTranslation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeArtisanProfileTranslation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeArtisanProfileTranslation))
			}
		}
	} else {
		s, ok := maybeArtisanProfileTranslation.(*[]*ArtisanProfileTranslation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeArtisanProfileTranslation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeArtisanProfileTranslation))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &artisanProfileTranslationR{}
		}
		args[object.ArtisanProfileID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &artisanProfileTranslationR{}
			}

			args[obj.ArtisanProfileID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`artisan_profiles`),
		qm.WhereIn(`artisan_profiles.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ArtisanProfile")
	}

	var resultSlice []*ArtisanProfile
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ArtisanProfile")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for artisan_profiles")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for artisan_profiles")
	}

	if len(artisanProfileAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ArtisanProfile = foreign
		if foreign.R == nil {
			foreign.R = &artisanProfileR{}
		}
		foreign.R.ArtisanProfileTranslations = append(foreign.R.ArtisanProfileTranslations, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ArtisanProfileID == foreign.ID {
				local.R.ArtisanProfile = foreign
				if foreign.R == nil {
					foreign.R = &artisanProfileR{}
				}
				foreign.R.ArtisanProfileTranslations = append(foreign.R.ArtisanProfileTranslations, local)
				break
			}
		}
	}

	return nil
}

// SetArtisanProfile of the artisanProfileTranslation to the related item.
// Sets o.R.ArtisanProfile to related.
// Adds o to related.R.ArtisanProfileTranslations.
func (o *ArtisanProfileTranslation) SetArtisanProfile(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ArtisanProfile) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"artisan_profile_translations\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"artisan_profile_id"}),
		strmangle.WhereClause("\"", "\"", 2, artisanProfileTranslationPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ArtisanProfileID, o.Locale}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ArtisanProfileID = related.ID
	if o.R == nil {
		o.R = &artisanProfileTranslationR{
			ArtisanProfile: related,
		}
	} else {
		o.R.ArtisanProfile = related
	}

	if related.R == nil {
		related.R = &artisanProfileR{
			ArtisanProfileTranslations: ArtisanProfileTranslationSlice{o},
		}
	} else {
		related.R.ArtisanProfileTranslations = append(related.R.ArtisanProfileTranslations, o)
	}

	return nil
}

// ArtisanProfileTranslations retrieves all the records using an executor.
func ArtisanProfileTranslations(mods ...qm.QueryMod) artisanProfileTranslationQuery {
	mods = append(mods, qm.From("\"artisan_profile_translations\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"artisan_profile_translations\".*"})
	}

	return artisanProfileTranslationQuery{q}
}

// FindArtisanProfileTranslation retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindArtisanProfileTranslation(ctx context.Context, exec boil.ContextExecutor, artisanProfileID string, locale string, selectCols ...string) (*ArtisanProfileTranslation, error) {
	artisanProfileTranslationObj := &ArtisanProfileTranslation{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"artisan_profile_translations\" where \"artisan_profile_id\"=$1 AND \"locale\"=$2", sel,
	)

	q := queries.Raw(query, artisanProfileID, locale)

	err := q.Bind(ctx, exec, artisanProfileTranslationObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from artisan_profile_translations")
	}

	if err = artisanProfileTranslationObj.doAfterSelectHooks(ctx, exec); err != nil {
		return artisanProfileTranslationObj, err
	}

	return artisanProfileTranslationObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ArtisanProfileTranslation) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no artisan_profile_translations provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(artisanProfileTranslationColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	artisanProfileTranslationInsertCacheMut.RLock()
	cache, cached := artisanProfileTranslationInsertCache[key]
	artisanProfileTranslationInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			artisanProfileTranslationAllColumns,
			artisanProfileTranslationColumnsWithDefault,
			artisanProfileTranslationColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(artisanProfileTranslationType, artisanProfileTranslationMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(artisanProfileTranslationType, artisanProfileTranslationMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"artisan_profile_translations\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"artisan_profile_translations\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into artisan_profile_translations")
	}

	if !cached {
		artisanProfileTranslationInsertCacheMut.Lock()
		artisanProfileTranslationInsertCache[key] = cache
		artisanProfileTranslationInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ArtisanProfileTranslation.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ArtisanProfileTranslation) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	artisanProfileTranslationUpdateCacheMut.RLock()
	cache, cached := artisanProfileTranslationUpdateCache[key]
	artisanProfileTranslationUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			artisanProfileTranslationAllColumns,
			artisanProfileTranslationPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update artisan_profile_translations, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"artisan_profile_translations\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, artisanProfileTranslationPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(artisanProfileTranslationType, artisanProfileTranslationMapping, append(wl, artisanProfileTranslationPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update artisan_profile_translations row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for artisan_profile_translations")
	}

	if !cached {
		artisanProfileTranslationUpdateCacheMut.Lock()
		artisanProfileTranslationUpdateCache[key] = cache
		artisanProfileTranslationUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q artisanProfileTranslationQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for artisan_profile_translations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for artisan_profile_translations")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ArtisanProfileTranslationSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), artisanProfileTranslationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"artisan_profile_translations\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, artisanProfileTranslationPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in artisanProfileTranslation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all artisanProfileTranslation")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ArtisanProfileTranslation) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no artisan_profile_translations provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(artisanProfileTranslationColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	artisanProfileTranslationUpsertCacheMut.RLock()
	cache, cached := artisanProfileTranslationUpsertCache[key]
	artisanProfileTranslationUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			artisanProfileTranslationAllColumns,
			artisanProfileTranslationColumnsWithDefault,
			artisanProfileTranslationColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			artisanProfileTranslationAllColumns,
			artisanProfileTranslationPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert artisan_profile_translations, could not build update column list")
		}

		ret := strmangle.SetComplement(artisanProfileTranslationAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(artisanProfileTranslationPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert artisan_profile_translations, could not build conflict column list")
			}

			conflict = make([]string, len(artisanProfileTranslationPrimaryKeyColumns))
			copy(conflict, artisanProfileTranslationPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"artisan_profile_translations\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(artisanProfileTranslationType, artisanProfileTranslationMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(artisanProfileTranslationType, artisanProfileTranslationMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert artisan_profile_translations")
	}

	if !cached {
		artisanProfileTranslationUpsertCacheMut.Lock()
		artisanProfileTranslationUpsertCache[key] = cache
		artisanProfileTranslationUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ArtisanProfileTranslation record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ArtisanProfileTranslation) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ArtisanProfileTranslation provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), artisanProfileTranslationPrimaryKeyMapping)
	sql := "DELETE FROM \"artisan_profile_translations\" WHERE \"artisan_profile_id\"=$1 AND \"locale\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from artisan_profile_translations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for artisan_profile_translations")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q artisanProfileTranslationQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no artisanProfileTranslationQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from artisan_profile_translations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for artisan_profile_translations")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ArtisanProfileTranslationSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(artisanProfileTranslationBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), artisanProfileTranslationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"artisan_profile_translations\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, artisanProfileTranslationPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from artisanProfileTranslation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for artisan_profile_translations")
	}

	if len(artisanProfileTranslationAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ArtisanProfileTranslation) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindArtisanProfileTranslation(ctx, exec, o.ArtisanProfileID, o.Locale)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ArtisanProfileTranslationSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ArtisanProfileTranslationSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), artisanProfileTranslationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"artisan_profile_translations\".* FROM \"artisan_profile_translations\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, artisanProfileTranslationPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ArtisanProfileTranslationSlice")
	}

	*o = slice

	return nil
}

// ArtisanProfileTranslationExists checks if the ArtisanProfileTranslation row exists.
func ArtisanProfileTranslationExists(ctx context.Context, exec boil.ContextExecutor, artisanProfileID string, locale string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"artisan_profile_translations\" where \"artisan_profile_id\"=$1 AND \"locale\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, artisanProfileID, locale)
	}
	row := exec.QueryRowContext(ctx, sql, artisanProfileID, locale)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if artisan_profile_translations exists")
	}

	return exists, nil
}

// Exists checks if the ArtisanProfileTranslation row exists.
func (o *ArtisanProfileTranslation) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ArtisanProfileTranslationExists(ctx, exec, o.ArtisanProfileID, o.Locale)
}
