// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ProductMedium is an object representing the database table.
type ProductMedium struct {
	ID               string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	ProductID        string      `boil:"product_id" json:"product_id" toml:"product_id" yaml:"product_id"`
	MediaKind        string      `boil:"media_kind" json:"media_kind" toml:"media_kind" yaml:"media_kind"`
	ObjectKey        string      `boil:"object_key" json:"object_key" toml:"object_key" yaml:"object_key"`
	OriginalFilename null.String `boil:"original_filename" json:"original_filename,omitempty" toml:"original_filename" yaml:"original_filename,omitempty"`
	MediaType        string      `boil:"media_type" json:"media_type" toml:"media_type" yaml:"media_type"`
	SizeBytes        int64       `boil:"size_bytes" json:"size_bytes" toml:"size_bytes" yaml:"size_bytes"`
	WidthPixels      null.Int    `boil:"width_pixels" json:"width_pixels,omitempty" toml:"width_pixels" yaml:"width_pixels,omitempty"`
	HeightPixels     null.Int    `boil:"height_pixels" json:"height_pixels,omitempty" toml:"height_pixels" yaml:"height_pixels,omitempty"`
	DurationSeconds  null.Int    `boil:"duration_seconds" json:"duration_seconds,omitempty" toml:"duration_seconds" yaml:"duration_seconds,omitempty"`
	ChecksumSha256   null.String `boil:"checksum_sha256" json:"checksum_sha256,omitempty" toml:"checksum_sha256" yaml:"checksum_sha256,omitempty"`
	AltText          null.String `boil:"alt_text" json:"alt_text,omitempty" toml:"alt_text" yaml:"alt_text,omitempty"`
	SortOrder        int         `boil:"sort_order" json:"sort_order" toml:"sort_order" yaml:"sort_order"`
	Visibility       string      `boil:"visibility" json:"visibility" toml:"visibility" yaml:"visibility"`
	CreatedAt        time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *productMediumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L productMediumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ProductMediumColumns = struct {
	ID               string
	ProductID        string
	MediaKind        string
	ObjectKey        string
	OriginalFilename string
	MediaType        string
	SizeBytes        string
	WidthPixels      string
	HeightPixels     string
	DurationSeconds  string
	ChecksumSha256   string
	AltText          string
	SortOrder        string
	Visibility       string
	CreatedAt        string
}{
	ID:               "id",
	ProductID:        "product_id",
	MediaKind:        "media_kind",
	ObjectKey:        "object_key",
	OriginalFilename: "original_filename",
	MediaType:        "media_type",
	SizeBytes:        "size_bytes",
	WidthPixels:      "width_pixels",
	HeightPixels:     "height_pixels",
	DurationSeconds:  "duration_seconds",
	ChecksumSha256:   "checksum_sha256",
	AltText:          "alt_text",
	SortOrder:        "sort_order",
	Visibility:       "visibility",
	CreatedAt:        "created_at",
}

var ProductMediumTableColumns = struct {
	ID               string
	ProductID        string
	MediaKind        string
	ObjectKey        string
	OriginalFilename string
	MediaType        string
	SizeBytes        string
	WidthPixels      string
	HeightPixels     string
	DurationSeconds  string
	ChecksumSha256   string
	AltText          string
	SortOrder        string
	Visibility       string
	CreatedAt        string
}{
	ID:               "product_media.id",
	ProductID:        "product_media.product_id",
	MediaKind:        "product_media.media_kind",
	ObjectKey:        "product_media.object_key",
	OriginalFilename: "product_media.original_filename",
	MediaType:        "product_media.media_type",
	SizeBytes:        "product_media.size_bytes",
	WidthPixels:      "product_media.width_pixels",
	HeightPixels:     "product_media.height_pixels",
	DurationSeconds:  "product_media.duration_seconds",
	ChecksumSha256:   "product_media.checksum_sha256",
	AltText:          "product_media.alt_text",
	SortOrder:        "product_media.sort_order",
	Visibility:       "product_media.visibility",
	CreatedAt:        "product_media.created_at",
}

// Generated where

var ProductMediumWhere = struct {
	ID               whereHelperstring
	ProductID        whereHelperstring
	MediaKind        whereHelperstring
	ObjectKey        whereHelperstring
	OriginalFilename whereHelpernull_String
	MediaType        whereHelperstring
	SizeBytes        whereHelperint64
	WidthPixels      whereHelpernull_Int
	HeightPixels     whereHelpernull_Int
	DurationSeconds  whereHelpernull_Int
	ChecksumSha256   whereHelpernull_String
	AltText          whereHelpernull_String
	SortOrder        whereHelperint
	Visibility       whereHelperstring
	CreatedAt        whereHelpertime_Time
}{
	ID:               whereHelperstring{field: "\"product_media\".\"id\""},
	ProductID:        whereHelperstring{field: "\"product_media\".\"product_id\""},
	MediaKind:        whereHelperstring{field: "\"product_media\".\"media_kind\""},
	ObjectKey:        whereHelperstring{field: "\"product_media\".\"object_key\""},
	OriginalFilename: whereHelpernull_String{field: "\"product_media\".\"original_filename\""},
	MediaType:        whereHelperstring{field: "\"product_media\".\"media_type\""},
	SizeBytes:        whereHelperint64{field: "\"product_media\".\"size_bytes\""},
	WidthPixels:      whereHelpernull_Int{field: "\"product_media\".\"width_pixels\""},
	HeightPixels:     whereHelpernull_Int{field: "\"product_media\".\"height_pixels\""},
	DurationSeconds:  whereHelpernull_Int{field: "\"product_media\".\"duration_seconds\""},
	ChecksumSha256:   whereHelpernull_String{field: "\"product_media\".\"checksum_sha256\""},
	AltText:          whereHelpernull_String{field: "\"product_media\".\"alt_text\""},
	SortOrder:        whereHelperint{field: "\"product_media\".\"sort_order\""},
	Visibility:       whereHelperstring{field: "\"product_media\".\"visibility\""},
	CreatedAt:        whereHelpertime_Time{field: "\"product_media\".\"created_at\""},
}

// ProductMediumRels is where relationship names are stored.
var ProductMediumRels = struct {
	Product string
}{
	Product: "Product",
}

// productMediumR is where relationships are stored.
type productMediumR struct {
	Product *Product `boil:"Product" json:"Product" toml:"Product" yaml:"Product"`
}

// NewStruct creates a new relationship struct
func (*productMediumR) NewStruct() *productMediumR {
	return &productMediumR{}
}

func (o *ProductMedium) GetProduct() *Product {
	if o == nil {
		return nil
	}

	return o.R.GetProduct()
}

func (r *productMediumR) GetProduct() *Product {
	if r == nil {
		return nil
	}

	return r.Product
}

// productMediumL is where Load methods for each relationship are stored.
type productMediumL struct{}

var (
	productMediumAllColumns            = []string{"id", "product_id", "media_kind", "object_key", "original_filename", "media_type", "size_bytes", "width_pixels", "height_pixels", "duration_seconds", "checksum_sha256", "alt_text", "sort_order", "visibility", "created_at"}
	productMediumColumnsWithoutDefault = []string{"product_id", "media_kind", "object_key", "media_type", "size_bytes"}
	productMediumColumnsWithDefault    = []string{"id", "original_filename", "width_pixels", "height_pixels", "duration_seconds", "checksum_sha256", "alt_text", "sort_order", "visibility", "created_at"}
	productMediumPrimaryKeyColumns     = []string{"id"}
	productMediumGeneratedColumns      = []string{}
)

type (
	// ProductMediumSlice is an alias for a slice of pointers to ProductMedium.
	// This should almost always be used instead of []ProductMedium.
	ProductMediumSlice []*ProductMedium
	// ProductMediumHook is the signature for custom ProductMedium hook methods
	ProductMediumHook func(context.Context, boil.ContextExecutor, *ProductMedium) error

	productMediumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	productMediumType                 = reflect.TypeOf(&ProductMedium{})
	productMediumMapping              = queries.MakeStructMapping(productMediumType)
	productMediumPrimaryKeyMapping, _ = queries.BindMapping(productMediumType, productMediumMapping, productMediumPrimaryKeyColumns)
	productMediumInsertCacheMut       sync.RWMutex
	productMediumInsertCache          = make(map[string]insertCache)
	productMediumUpdateCacheMut       sync.RWMutex
	productMediumUpdateCache          = make(map[string]updateCache)
	productMediumUpsertCacheMut       sync.RWMutex
	productMediumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var productMediumAfterSelectMu sync.Mutex
var productMediumAfterSelectHooks []ProductMediumHook

var productMediumBeforeInsertMu sync.Mutex
var productMediumBeforeInsertHooks []ProductMediumHook
var productMediumAfterInsertMu sync.Mutex
var productMediumAfterInsertHooks []ProductMediumHook

var productMediumBeforeUpdateMu sync.Mutex
var productMediumBeforeUpdateHooks []ProductMediumHook
var productMediumAfterUpdateMu sync.Mutex
var productMediumAfterUpdateHooks []ProductMediumHook

var productMediumBeforeDeleteMu sync.Mutex
var productMediumBeforeDeleteHooks []ProductMediumHook
var productMediumAfterDeleteMu sync.Mutex
var productMediumAfterDeleteHooks []ProductMediumHook

var productMediumBeforeUpsertMu sync.Mutex
var productMediumBeforeUpsertHooks []ProductMediumHook
var productMediumAfterUpsertMu sync.Mutex
var productMediumAfterUpsertHooks []ProductMediumHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ProductMedium) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productMediumAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ProductMedium) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productMediumBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ProductMedium) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productMediumAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ProductMedium) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productMediumBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ProductMedium) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productMediumAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ProductMedium) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productMediumBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ProductMedium) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productMediumAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ProductMedium) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productMediumBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ProductMedium) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productMediumAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddProductMediumHook registers your hook function for all future operations.
func AddProductMediumHook(hookPoint boil.HookPoint, productMediumHook ProductMediumHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		productMediumAfterSelectMu.Lock()
		productMediumAfterSelectHooks = append(productMediumAfterSelectHooks, productMediumHook)
		productMediumAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		productMediumBeforeInsertMu.Lock()
		productMediumBeforeInsertHooks = append(productMediumBeforeInsertHooks, productMediumHook)
		productMediumBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		productMediumAfterInsertMu.Lock()
		productMediumAfterInsertHooks = append(productMediumAfterInsertHooks, productMediumHook)
		productMediumAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		productMediumBeforeUpdateMu.Lock()
		productMediumBeforeUpdateHooks = append(productMediumBeforeUpdateHooks, productMediumHook)
		productMediumBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		productMediumAfterUpdateMu.Lock()
		productMediumAfterUpdateHooks = append(productMediumAfterUpdateHooks, productMediumHook)
		productMediumAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		productMediumBeforeDeleteMu.Lock()
		productMediumBeforeDeleteHooks = append(productMediumBeforeDeleteHooks, productMediumHook)
		productMediumBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		productMediumAfterDeleteMu.Lock()
		productMediumAfterDeleteHooks = append(productMediumAfterDeleteHooks, productMediumHook)
		productMediumAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		productMediumBeforeUpsertMu.Lock()
		productMediumBeforeUpsertHooks = append(productMediumBeforeUpsertHooks, productMediumHook)
		productMediumBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		productMediumAfterUpsertMu.Lock()
		productMediumAfterUpsertHooks = append(productMediumAfterUpsertHooks, productMediumHook)
		productMediumAfterUpsertMu.Unlock()
	}
}

// One returns a single productMedium record from the query.
func (q productMediumQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ProductMedium, error) {
	o := &ProductMedium{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for product_media")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ProductMedium records from the query.
func (q productMediumQuery) All(ctx context.Context, exec boil.ContextExecutor) (ProductMediumSlice, error) {
	var o []*ProductMedium

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ProductMedium slice")
	}

	if len(productMediumAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ProductMedium records in the query.
func (q productMediumQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count product_media rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q productMediumQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if product_media exists")
	}

	return count > 0, nil
}

// Product pointed to by the foreign key.
func (o *ProductMedium) Product(mods ...qm.QueryMod) productQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ProductID),
	}

	queryMods = append(queryMods, mods...)

	return Products(queryMods...)
}

// LoadProduct allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (productMediumL) LoadProduct(ctx context.Context, e boil.ContextExecutor, singular bool, maybeProductMedium interface{}, mods queries.Applicator) error {
	var slice []*ProductMedium
	var object *ProductMedium

	if singular {
		var ok bool
		object, ok = maybeProductMedium.(*ProductMedium)
		if !ok {
			object = new(ProductMedium)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeProductMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeProductMedium))
			}
		}
	} else {
		s, ok := maybeProductMedium.(*[]*ProductMedium)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeProductMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeProductMedium))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &productMediumR{}
		}
		args[object.ProductID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &productMediumR{}
			}

			args[obj.ProductID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`products`),
		qm.WhereIn(`products.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Product")
	}

	var resultSlice []*Product
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Product")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for products")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for products")
	}

	if len(productAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Product = foreign
		if foreign.R == nil {
			foreign.R = &productR{}
		}
		foreign.R.ProductMedia = append(foreign.R.ProductMedia, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ProductID == foreign.ID {
				local.R.Product = foreign
				if foreign.R == nil {
					foreign.R = &productR{}
				}
				foreign.R.ProductMedia = append(foreign.R.ProductMedia, local)
				break
			}
		}
	}

	return nil
}

// SetProduct of the productMedium to the related item.
// Sets o.R.Product to related.
// Adds o to related.R.ProductMedia.
func (o *ProductMedium) SetProduct(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Product) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"product_media\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"product_id"}),
		strmangle.WhereClause("\"", "\"", 2, productMediumPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ProductID = related.ID
	if o.R == nil {
		o.R = &productMediumR{
			Product: related,
		}
	} else {
		o.R.Product = related
	}

	if related.R == nil {
		related.R = &productR{
			ProductMedia: ProductMediumSlice{o},
		}
	} else {
		related.R.ProductMedia = append(related.R.ProductMedia, o)
	}

	return nil
}

// ProductMedia retrieves all the records using an executor.
func ProductMedia(mods ...qm.QueryMod) productMediumQuery {
	mods = append(mods, qm.From("\"product_media\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"product_media\".*"})
	}

	return productMediumQuery{q}
}

// FindProductMedium retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindProductMedium(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*ProductMedium, error) {
	productMediumObj := &ProductMedium{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"product_media\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, productMediumObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from product_media")
	}

	if err = productMediumObj.doAfterSelectHooks(ctx, exec); err != nil {
		return productMediumObj, err
	}

	return productMediumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ProductMedium) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no product_media provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(productMediumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	productMediumInsertCacheMut.RLock()
	cache, cached := productMediumInsertCache[key]
	productMediumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			productMediumAllColumns,
			productMediumColumnsWithDefault,
			productMediumColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(productMediumType, productMediumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(productMediumType, productMediumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"product_media\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"product_media\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into product_media")
	}

	if !cached {
		productMediumInsertCacheMut.Lock()
		productMediumInsertCache[key] = cache
		productMediumInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ProductMedium.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ProductMedium) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	productMediumUpdateCacheMut.RLock()
	cache, cached := productMediumUpdateCache[key]
	productMediumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			productMediumAllColumns,
			productMediumPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update product_media, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"product_media\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, productMediumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(productMediumType, productMediumMapping, append(wl, productMediumPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update product_media row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for product_media")
	}

	if !cached {
		productMediumUpdateCacheMut.Lock()
		productMediumUpdateCache[key] = cache
		productMediumUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q productMediumQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for product_media")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for product_media")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ProductMediumSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), productMediumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"product_media\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, productMediumPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in productMedium slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all productMedium")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ProductMedium) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no product_media provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(productMediumColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	productMediumUpsertCacheMut.RLock()
	cache, cached := productMediumUpsertCache[key]
	productMediumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			productMediumAllColumns,
			productMediumColumnsWithDefault,
			productMediumColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			productMediumAllColumns,
			productMediumPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert product_media, could not build update column list")
		}

		ret := strmangle.SetComplement(productMediumAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(productMediumPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert product_media, could not build conflict column list")
			}

			conflict = make([]string, len(productMediumPrimaryKeyColumns))
			copy(conflict, productMediumPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"product_media\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(productMediumType, productMediumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(productMediumType, productMediumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert product_media")
	}

	if !cached {
		productMediumUpsertCacheMut.Lock()
		productMediumUpsertCache[key] = cache
		productMediumUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ProductMedium record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ProductMedium) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ProductMedium provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), productMediumPrimaryKeyMapping)
	sql := "DELETE FROM \"product_media\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from product_media")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for product_media")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q productMediumQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no productMediumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from product_media")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for product_media")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ProductMediumSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(productMediumBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), productMediumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"product_media\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, productMediumPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from productMedium slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for product_media")
	}

	if len(productMediumAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ProductMedium) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindProductMedium(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProductMediumSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ProductMediumSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), productMediumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"product_media\".* FROM \"product_media\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, productMediumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ProductMediumSlice")
	}

	*o = slice

	return nil
}

// ProductMediumExists checks if the ProductMedium row exists.
func ProductMediumExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"product_media\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if product_media exists")
	}

	return exists, nil
}

// Exists checks if the ProductMedium row exists.
func (o *ProductMedium) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ProductMediumExists(ctx, exec, o.ID)
}
