import type { Locale } from "./i18n";

const en = { required: "This field is required.", email: "Enter a valid email address.", name: "Enter at least 2 characters.", password: "Use at least 12 characters.", passwordMatch: "Passwords do not match.", phone: "Enter a valid phone number.", address: "Enter a complete address.", formInvalid: "Please correct the highlighted fields.", backendError: "We could not submit the form. Please try again.", unavailable: "This service is temporarily unavailable.", terms: "You must accept the terms to continue." };
export type FormCopy = typeof en;
const fr: FormCopy = { required: "Ce champ est obligatoire.", email: "Saisissez une adresse e-mail valide.", name: "Saisissez au moins 2 caractères.", password: "Utilisez au moins 12 caractères.", passwordMatch: "Les mots de passe ne correspondent pas.", phone: "Saisissez un numéro de téléphone valide.", address: "Saisissez une adresse complète.", formInvalid: "Corrigez les champs indiqués.", backendError: "Le formulaire n’a pas pu être envoyé. Réessayez.", unavailable: "Ce service est temporairement indisponible.", terms: "Vous devez accepter les conditions pour continuer." };
const ar: FormCopy = { required: "هذا الحقل مطلوب.", email: "أدخل عنوان بريد إلكتروني صالحاً.", name: "أدخل حرفين على الأقل.", password: "استخدم 12 حرفاً على الأقل.", passwordMatch: "كلمتا المرور غير متطابقتين.", phone: "أدخل رقم هاتف صالحاً.", address: "أدخل عنواناً كاملاً.", formInvalid: "يرجى تصحيح الحقول المحددة.", backendError: "تعذر إرسال النموذج. يرجى المحاولة مجدداً.", unavailable: "هذه الخدمة غير متاحة مؤقتاً.", terms: "يجب الموافقة على الشروط للمتابعة." };
const es: FormCopy = { required: "Este campo es obligatorio.", email: "Introduce un correo electrónico válido.", name: "Introduce al menos 2 caracteres.", password: "Utiliza al menos 12 caracteres.", passwordMatch: "Las contraseñas no coinciden.", phone: "Introduce un número de teléfono válido.", address: "Introduce una dirección completa.", formInvalid: "Corrige los campos indicados.", backendError: "No se pudo enviar el formulario. Inténtalo de nuevo.", unavailable: "Este servicio no está disponible temporalmente.", terms: "Debes aceptar los términos para continuar." };

export function formCopy(locale: Locale): FormCopy { return { en, fr, ar, es }[locale]; }
